// BL-097: renderer only - no metric derivation happens here. Every number
// on screen comes straight from backlog.json, generated by
// extension/src/metrics/backlogDashboard.ts via the same computeDeliveryMetrics
// the swarm-metrics CLI uses.
(function () {
  'use strict';

  var DASHBOARD_URL = './backlog.json';
  var SVG_NS = 'http://www.w3.org/2000/svg';

  function el(tag, attrs, children) {
    var node = document.createElement(tag);
    if (attrs) {
      for (var k in attrs) {
        node.setAttribute(k, attrs[k]);
      }
    }
    (children || []).forEach(function (c) {
      node.appendChild(typeof c === 'string' ? document.createTextNode(c) : c);
    });
    return node;
  }

  function svgEl(tag, attrs) {
    var node = document.createElementNS(SVG_NS, tag);
    if (attrs) {
      for (var k in attrs) {
        node.setAttribute(k, attrs[k]);
      }
    }
    return node;
  }

  // A minimal, dependency-free bar chart (no charting library - the page
  // must stay self-contained, no CDN, per dashboard-03).
  function barChart(series, width, height) {
    var container = svgEl('svg', { viewBox: '0 0 ' + width + ' ' + height, width: '100%', height: height });
    if (!series || series.length === 0) {
      return container;
    }
    var max = Math.max.apply(
      null,
      series.map(function (p) { return p.value; }).concat([1])
    );
    var barWidth = width / series.length;
    series.forEach(function (p, i) {
      var barHeight = max > 0 ? (p.value / max) * (height - 4) : 0;
      var rect = svgEl('rect', {
        x: i * barWidth + 1,
        y: height - barHeight,
        width: Math.max(1, barWidth - 2),
        height: barHeight,
        fill: '#5fb0ff',
      });
      var title = document.createElementNS(SVG_NS, 'title');
      title.textContent = String(p.periodStart).slice(0, 10) + ': ' + p.value;
      rect.appendChild(title);
      container.appendChild(rect);
    });
    return container;
  }

  function trendArrow(trend) {
    if (!trend || trend.direction === 'unknown') {
      return '';
    }
    if (trend.direction === 'up') {
      return ' ▲';
    }
    if (trend.direction === 'down') {
      return ' ▼';
    }
    return ' ▬';
  }

  function renderTicketList(container, title, tickets) {
    container.appendChild(el('h3', {}, [title + ' (' + tickets.length + ')']));
    var list = el('ul', {});
    tickets.forEach(function (t) {
      var badge = t.swarm && t.swarm !== 'primary' ? ' [' + t.swarm + ']' : '';
      var eta = t.p50Iso ? ' — ETA ' + t.p50Iso.slice(0, 10) : '';
      list.appendChild(el('li', {}, [t.id + ' — ' + t.title + badge + eta]));
    });
    container.appendChild(list);
  }

  function renderBoard(board) {
    var container = document.getElementById('board');
    container.innerHTML = '';
    renderTicketList(container, 'Active', board.active);
    renderTicketList(container, 'Paused', board.paused);

    container.appendChild(el('h3', {}, ['Done by milestone']));
    var milestones = Object.keys(board.doneByMilestone).sort();
    var doneList = el('ul', {});
    milestones.forEach(function (m) {
      doneList.appendChild(el('li', {}, [m + ': ' + board.doneByMilestone[m].length]));
    });
    container.appendChild(doneList);
  }

  function renderVelocity(velocity) {
    var container = document.getElementById('velocity');
    container.innerHTML = '';
    container.appendChild(
      el('p', {}, ['Trailing ' + velocity.rollingWindowDays + 'd: ' + velocity.rollingWindowCount + ' closed' + trendArrow(velocity.trend)])
    );
    container.appendChild(barChart(velocity.weeklySeries, 300, 80));
  }

  function renderBurndown(burndown) {
    var container = document.getElementById('burndown');
    container.innerHTML = '';
    if (!burndown || burndown.length === 0) {
      container.appendChild(el('p', {}, ['No milestones yet.']));
      return;
    }
    burndown.forEach(function (m) {
      container.appendChild(el('h4', {}, [m.milestone + ': ' + m.currentRemaining + ' remaining' + trendArrow(m.trend)]));
      container.appendChild(barChart(m.dailySeries, 300, 60));
    });
  }

  function renderCycleTime(cycleTime) {
    var container = document.getElementById('cycleTime');
    container.innerHTML = '';
    if (cycleTime.medianMs === null) {
      container.appendChild(el('p', {}, ['No closed tickets yet.']));
      return;
    }
    var medianH = Math.round(cycleTime.medianMs / 3600000);
    var p85H = Math.round(cycleTime.p85Ms / 3600000);
    container.appendChild(
      el('p', {}, ['Median ' + medianH + 'h, p85 ' + p85H + 'h over ' + cycleTime.sampleCount + ' ticket(s)' + trendArrow(cycleTime.trend)])
    );
  }

  function renderAll(data) {
    var asOf = document.getElementById('asOf');
    var shaText = data.sourceSha ? ' (' + data.sourceSha.slice(0, 10) + ')' : '';
    asOf.textContent = 'As of ' + new Date(data.generatedAtIso).toLocaleString() + shaText;
    renderBoard(data.board);
    renderVelocity(data.metrics.velocity);
    renderBurndown(data.metrics.burndown);
    renderCycleTime(data.metrics.cycleTime);
  }

  function registerServiceWorker() {
    if (!('serviceWorker' in navigator)) {
      return Promise.resolve(null);
    }
    return navigator.serviceWorker.register('./sw.js').catch(function () {
      return null;
    });
  }

  // BL-097 dashboard-06/07: Periodic Background Sync is Android/Chrome-only
  // and requires the PWA to be installed with the permission granted -
  // every step here is feature-detected so an unsupported browser
  // (dashboard-07) never sees an error or a permission prompt it can't
  // satisfy; freshness there is just open-time fetch plus whatever the
  // service worker already caches.
  function registerPeriodicSync(registration) {
    if (!registration || !('periodicSync' in registration) || !('permissions' in navigator)) {
      return;
    }
    navigator.permissions
      .query({ name: 'periodic-background-sync' })
      .then(function (status) {
        if (status.state !== 'granted') {
          return;
        }
        return registration.periodicSync.register('refresh-backlog-json', { minInterval: 2 * 60 * 60 * 1000 });
      })
      .catch(function () {
        // Unsupported permission name, or registration rejected (e.g. the
        // browser's own site-engagement heuristics aren't met yet) - silent,
        // per dashboard-07's "no error or prompt" requirement.
      });
  }

  fetch(DASHBOARD_URL)
    .then(function (res) {
      return res.json();
    })
    .then(renderAll)
    .catch(function () {
      document.getElementById('asOf').textContent = 'Could not load backlog.json (offline and nothing cached yet).';
    });

  registerServiceWorker().then(registerPeriodicSync);
})();
