// BL-097: renderer only - no metric derivation happens here. Every number
// on screen comes straight from backlog.json, generated by
// extension/src/metrics/backlogDashboard.ts via the same computeDeliveryMetrics
// the swarm-metrics CLI uses.
(function () {
  'use strict';

  var DASHBOARD_URL = './backlog.json';
  var DOCS_TREE_URL = './docs-tree.json';
  var SVG_NS = 'http://www.w3.org/2000/svg';

  function el(tag, attrs, children) {
    var node = document.createElement(tag);
    if (attrs) {
      for (var k in attrs) {
        node.setAttribute(k, attrs[k]);
      }
    }
    (children || []).forEach(function (c) {
      node.appendChild(typeof c === 'string' ? document.createTextNode(c) : c);
    });
    return node;
  }

  function svgEl(tag, attrs) {
    var node = document.createElementNS(SVG_NS, tag);
    if (attrs) {
      for (var k in attrs) {
        node.setAttribute(k, attrs[k]);
      }
    }
    return node;
  }

  // A minimal, dependency-free bar chart (no charting library - the page
  // must stay self-contained, no CDN, per dashboard-03).
  function barChart(series, width, height) {
    var container = svgEl('svg', { viewBox: '0 0 ' + width + ' ' + height, width: '100%', height: height });
    if (!series || series.length === 0) {
      return container;
    }
    var max = Math.max.apply(
      null,
      series.map(function (p) { return p.value; }).concat([1])
    );
    var barWidth = width / series.length;
    series.forEach(function (p, i) {
      var barHeight = max > 0 ? (p.value / max) * (height - 4) : 0;
      var rect = svgEl('rect', {
        x: i * barWidth + 1,
        y: height - barHeight,
        width: Math.max(1, barWidth - 2),
        height: barHeight,
        fill: '#5fb0ff',
      });
      var title = document.createElementNS(SVG_NS, 'title');
      title.textContent = String(p.periodStart).slice(0, 10) + ': ' + p.value;
      rect.appendChild(title);
      container.appendChild(rect);
    });
    return container;
  }

  function trendArrow(trend) {
    if (!trend || trend.direction === 'unknown') {
      return '';
    }
    if (trend.direction === 'up') {
      return ' ▲';
    }
    if (trend.direction === 'down') {
      return ' ▼';
    }
    return ' ▬';
  }

  function renderTicketList(container, title, tickets) {
    container.appendChild(el('h3', {}, [title + ' (' + tickets.length + ')']));
    var list = el('ul', {});
    tickets.forEach(function (t) {
      var badge = t.swarm && t.swarm !== 'primary' ? ' [' + t.swarm + ']' : '';
      var eta = t.p50Iso ? ' — ETA ' + t.p50Iso.slice(0, 10) : '';
      list.appendChild(el('li', {}, [t.id + ' — ' + t.title + badge + eta]));
    });
    container.appendChild(list);
  }

  function renderBoard(board) {
    var container = document.getElementById('board');
    container.innerHTML = '';
    renderTicketList(container, 'Active', board.active);
    renderTicketList(container, 'Paused', board.paused);

    container.appendChild(el('h3', {}, ['Done by milestone']));
    var milestones = Object.keys(board.doneByMilestone).sort();
    var doneList = el('ul', {});
    milestones.forEach(function (m) {
      doneList.appendChild(el('li', {}, [m + ': ' + board.doneByMilestone[m].length]));
    });
    container.appendChild(doneList);
  }

  function renderVelocity(velocity) {
    var container = document.getElementById('velocity');
    container.innerHTML = '';
    container.appendChild(
      el('p', {}, ['Trailing ' + velocity.rollingWindowDays + 'd: ' + velocity.rollingWindowCount + ' closed' + trendArrow(velocity.trend)])
    );
    container.appendChild(barChart(velocity.weeklySeries, 300, 80));
  }

  function renderBurndown(burndown) {
    var container = document.getElementById('burndown');
    container.innerHTML = '';
    if (!burndown || burndown.length === 0) {
      container.appendChild(el('p', {}, ['No milestones yet.']));
      return;
    }
    burndown.forEach(function (m) {
      container.appendChild(el('h4', {}, [m.milestone + ': ' + m.currentRemaining + ' remaining' + trendArrow(m.trend)]));
      container.appendChild(barChart(m.dailySeries, 300, 60));
    });
  }

  function renderCycleTime(cycleTime) {
    var container = document.getElementById('cycleTime');
    container.innerHTML = '';
    if (cycleTime.medianMs === null) {
      container.appendChild(el('p', {}, ['No closed tickets yet.']));
      return;
    }
    var medianH = Math.round(cycleTime.medianMs / 3600000);
    var p85H = Math.round(cycleTime.p85Ms / 3600000);
    container.appendChild(
      el('p', {}, ['Median ' + medianH + 'h, p85 ' + p85H + 'h over ' + cycleTime.sampleCount + ' ticket(s)' + trendArrow(cycleTime.trend)])
    );
  }

  function renderAll(data) {
    var asOf = document.getElementById('asOf');
    var shaText = data.sourceSha ? ' (' + data.sourceSha.slice(0, 10) + ')' : '';
    asOf.textContent = 'As of ' + new Date(data.generatedAtIso).toLocaleString() + shaText;
    renderBoard(data.board);
    renderVelocity(data.metrics.velocity);
    renderBurndown(data.metrics.burndown);
    renderCycleTime(data.metrics.cycleTime);
  }

  // BL-117: read-only documentation drill-down (vision -> milestone ->
  // ticket -> Gherkin). No affordance anywhere in this explorer edits
  // documentation or creates/modifies tickets (docs-drilldown-05) - every
  // control below only ever navigates docsView and re-renders from the
  // already-fetched docsTree, never writes anything back to the network.
  var docsTree = null;
  var docsView = { level: 'root' };

  function findMilestone(name) {
    return (docsTree.milestones || []).find(function (m) { return m.milestone === name; });
  }

  function findTicket(id) {
    return (docsTree.tickets || []).find(function (t) { return t.id === id; });
  }

  function findVisionDoc(id) {
    return (docsTree.vision || []).find(function (v) { return v.id === id; });
  }

  function navButton(label, view) {
    var btn = el('button', { type: 'button', class: 'docs-list-item' }, [label]);
    btn.addEventListener('click', function () {
      docsView = view;
      renderDocsExplorer();
    });
    return btn;
  }

  function renderDocsCrumbs() {
    var container = document.getElementById('docsCrumbs');
    container.innerHTML = '';
    var crumbs = [{ label: 'Documentation', view: { level: 'root' } }];
    if (docsView.level === 'vision') {
      var doc = findVisionDoc(docsView.docId);
      crumbs.push({ label: doc ? doc.title : docsView.docId, view: docsView });
    } else if (docsView.level === 'milestone' || docsView.level === 'ticket' || docsView.level === 'scenario') {
      crumbs.push({ label: docsView.milestone, view: { level: 'milestone', milestone: docsView.milestone } });
    }
    if (docsView.level === 'ticket' || docsView.level === 'scenario') {
      crumbs.push({ label: docsView.ticketId, view: { level: 'ticket', milestone: docsView.milestone, ticketId: docsView.ticketId } });
    }
    if (docsView.level === 'scenario') {
      var ticket = findTicket(docsView.ticketId);
      var scenario = ticket && ticket.scenarios[docsView.scenarioIndex];
      crumbs.push({ label: scenario ? scenario.name : 'scenario', view: docsView });
    }
    crumbs.forEach(function (crumb, i) {
      if (i > 0) {
        container.appendChild(document.createTextNode(' › '));
      }
      var isCurrent = i === crumbs.length - 1;
      if (isCurrent) {
        container.appendChild(el('strong', {}, [crumb.label]));
        return;
      }
      var link = el('button', { type: 'button' }, [crumb.label]);
      link.addEventListener('click', function () {
        docsView = crumb.view;
        renderDocsExplorer();
      });
      container.appendChild(link);
    });
  }

  function renderDocsRoot(container) {
    container.appendChild(el('h3', {}, ['Vision']));
    (docsTree.vision || []).forEach(function (doc) {
      container.appendChild(navButton(doc.title, { level: 'vision', docId: doc.id }));
    });
    container.appendChild(el('h3', {}, ['Milestones']));
    (docsTree.milestones || []).forEach(function (m) {
      container.appendChild(navButton(m.milestone + ' (' + m.tickets.length + ')', { level: 'milestone', milestone: m.milestone }));
    });
  }

  function renderDocsVision(container) {
    var doc = findVisionDoc(docsView.docId);
    if (!doc) {
      container.appendChild(noDataParagraph('document not found'));
      return;
    }
    container.appendChild(el('pre', { class: 'doc-content' }, [doc.content]));
  }

  function renderDocsMilestone(container) {
    var milestone = findMilestone(docsView.milestone);
    if (!milestone) {
      container.appendChild(noDataParagraph('milestone not found'));
      return;
    }
    milestone.tickets.forEach(function (t) {
      container.appendChild(navButton(t.id + ' — ' + t.title + ' [' + t.status + ']', {
        level: 'ticket', milestone: docsView.milestone, ticketId: t.id,
      }));
    });
  }

  function renderDocsTicket(container) {
    var ticket = findTicket(docsView.ticketId);
    if (!ticket) {
      container.appendChild(noDataParagraph('ticket not found'));
      return;
    }
    container.appendChild(el('p', {}, [ticket.title + ' [' + ticket.status + ']' + (ticket.priority !== undefined ? ' priority ' + ticket.priority : '')]));
    container.appendChild(el('p', {}, [ticket.description || 'No description.']));
    container.appendChild(el('h4', {}, ['Acceptance scenarios']));
    if (!ticket.scenarios || ticket.scenarios.length === 0) {
      container.appendChild(noDataParagraph('no scenarios resolved for this ticket'));
      return;
    }
    ticket.scenarios.forEach(function (s, i) {
      container.appendChild(navButton(s.name, { level: 'scenario', milestone: docsView.milestone, ticketId: docsView.ticketId, scenarioIndex: i }));
    });
  }

  function renderDocsScenario(container) {
    var ticket = findTicket(docsView.ticketId);
    var scenario = ticket && ticket.scenarios[docsView.scenarioIndex];
    if (!scenario) {
      container.appendChild(noDataParagraph('scenario not found'));
      return;
    }
    container.appendChild(el('pre', { class: 'gherkin' }, [scenario.text]));
  }

  function renderDocsExplorer() {
    var container = document.getElementById('docsExplorer');
    container.innerHTML = '';
    if (!docsTree) {
      container.appendChild(noDataParagraph('documentation not available'));
      return;
    }
    renderDocsCrumbs();
    if (docsView.level === 'vision') {
      renderDocsVision(container);
    } else if (docsView.level === 'milestone') {
      renderDocsMilestone(container);
    } else if (docsView.level === 'ticket') {
      renderDocsTicket(container);
    } else if (docsView.level === 'scenario') {
      renderDocsScenario(container);
    } else {
      renderDocsRoot(container);
    }
  }

  function noDataParagraph(text) {
    return el('p', {}, [text || 'no data']);
  }

  function renderDocsTree(data) {
    docsTree = data;
    var asOf = document.getElementById('docsAsOf');
    var shaText = data.sourceSha ? ' (' + data.sourceSha.slice(0, 10) + ')' : '';
    // BL-117 docs-drilldown-04: labeled with the commit/timestamp it was
    // rendered from, same honesty requirement as the backlog board.
    asOf.textContent = 'As of ' + new Date(data.generatedAtIso).toLocaleString() + shaText;
    renderDocsExplorer();
  }

  function registerServiceWorker() {
    if (!('serviceWorker' in navigator)) {
      return Promise.resolve(null);
    }
    return navigator.serviceWorker.register('./sw.js').catch(function () {
      return null;
    });
  }

  // BL-097 dashboard-06/07: Periodic Background Sync is Android/Chrome-only
  // and requires the PWA to be installed with the permission granted -
  // every step here is feature-detected so an unsupported browser
  // (dashboard-07) never sees an error or a permission prompt it can't
  // satisfy; freshness there is just open-time fetch plus whatever the
  // service worker already caches.
  function registerPeriodicSync(registration) {
    if (!registration || !('periodicSync' in registration) || !('permissions' in navigator)) {
      return;
    }
    navigator.permissions
      .query({ name: 'periodic-background-sync' })
      .then(function (status) {
        if (status.state !== 'granted') {
          return;
        }
        return registration.periodicSync.register('refresh-backlog-json', { minInterval: 2 * 60 * 60 * 1000 });
      })
      .catch(function () {
        // Unsupported permission name, or registration rejected (e.g. the
        // browser's own site-engagement heuristics aren't met yet) - silent,
        // per dashboard-07's "no error or prompt" requirement.
      });
  }

  fetch(DASHBOARD_URL)
    .then(function (res) {
      return res.json();
    })
    .then(renderAll)
    .catch(function () {
      document.getElementById('asOf').textContent = 'Could not load backlog.json (offline and nothing cached yet).';
    });

  fetch(DOCS_TREE_URL)
    .then(function (res) {
      return res.json();
    })
    .then(renderDocsTree)
    .catch(function () {
      document.getElementById('docsAsOf').textContent = 'Could not load docs-tree.json (offline and nothing cached yet).';
    });

  registerServiceWorker().then(registerPeriodicSync);
})();
