// BL-097: renderer only - no metric derivation happens here. Every number
// on screen comes straight from backlog.json, generated by
// extension/src/metrics/backlogDashboard.ts via the same computeDeliveryMetrics
// the swarm-metrics CLI uses.
(function () {
  'use strict';

  var DASHBOARD_URL = './backlog.json';
  var DOCS_TREE_URL = './docs-tree.json';
  var RECERT_BATCH_URL = './recert-batch.json';
  var SVG_NS = 'http://www.w3.org/2000/svg';
  // BL-223: the inbound address comes from recert-batch.json's own
  // recertEmailTo field (recertificationStore.ts's readRecertEmailTo,
  // swarmforge.conf's recert_email_to - never hardcoded here a second time,
  // so a future custom-domain swap is a config change only). This fallback
  // only covers recertBatch not having loaded/lacking the field yet - it is
  // never the reserved .invalid TLD, which can never resolve.
  var RECERT_EMAIL_FALLBACK = 'recert@tolokarooo.resend.app';

  // BL-118: bilingual chrome + content. English is always the first-launch
  // default (bilingual-01) regardless of browser locale - currentLocale
  // only ever changes via the visible toggle, never navigator.language.
  // Persistence goes through Cache Storage (bilingual-02's "no other browser
  // storage"), not localStorage - see PREFERENCES_CACHE_NAME below.
  var currentLocale = 'en';
  // BL-249 hardener bounce: PERMANENTLY static, deliberately distinct from
  // sw.js's own CACHE_NAME (which is content-hash-stamped per deploy - see
  // pwa/sw.js). sw.js's activate handler explicitly exempts this exact name
  // from its per-deploy purge (its own PREFERENCES_CACHE_NAME, kept in sync
  // by hand - sw.js and app.js share no module system). Never rename/stamp
  // this without also updating sw.js's exemption, or a shell-changing
  // deploy will silently wipe every returning user's locale and font-size
  // preference again.
  var PREFERENCES_CACHE_NAME = 'swarmforge-dashboard-preferences';
  var LOCALE_PREF_KEY = './__locale-preference__';
  var lastBacklogData = null;

  // BL-220: every view sizes its text in rem, relative to the root (html)
  // font-size, so that root is the single knob that scales the whole app.
  // Persistence reuses the SAME Cache Storage instance as the locale
  // preference above (a new key), never localStorage/sessionStorage.
  var DEFAULT_FONT_SIZE_PX = 28;
  var FONT_SIZE_STEP_PX = 2;
  var MIN_FONT_SIZE_PX = 16;
  var MAX_FONT_SIZE_PX = 40;
  var FONT_SIZE_PREF_KEY = './__font-size-preference__';
  var currentFontSizePx = DEFAULT_FONT_SIZE_PX;

  function tr(key) {
    var dict = (window.LOCALES && window.LOCALES[currentLocale]) || {};
    var fallback = (window.LOCALES && window.LOCALES.en) || {};
    return dict[key] || fallback[key] || key;
  }

  // bilingual-01/02: every static UI-chrome string in index.html carries
  // data-i18n="<catalog key>" - this is the one pass that ever reads it,
  // applied on load and again on every toggle. Dynamic content (ticket
  // titles, doc content, "As of ..." timestamps) is handled by each
  // section's own render function re-running with the new locale instead,
  // never by this pass - it only ever touches static chrome nodes.
  function applyChromeLocale() {
    document.title = tr('pageTitle');
    var toggle = document.getElementById('localeToggle');
    if (toggle) {
      toggle.textContent = tr('localeToggleLabel');
    }
    var nodes = document.querySelectorAll('[data-i18n]');
    for (var i = 0; i < nodes.length; i++) {
      nodes[i].textContent = tr(nodes[i].getAttribute('data-i18n'));
    }
    // BL-220: accessible labels (aria-label) for chrome controls whose
    // visible text stays universal (e.g. "A-"/"A+"), mirroring the
    // data-i18n pass above but targeting an attribute instead of textContent.
    var ariaNodes = document.querySelectorAll('[data-i18n-aria]');
    for (var j = 0; j < ariaNodes.length; j++) {
      ariaNodes[j].setAttribute('aria-label', tr(ariaNodes[j].getAttribute('data-i18n-aria')));
    }
    // BL-254: same pass, targeting a placeholder attribute - the search
    // box's placeholder is chrome text (not spec content), so it goes
    // through locale like every other static label above.
    var placeholderNodes = document.querySelectorAll('[data-i18n-placeholder]');
    for (var k = 0; k < placeholderNodes.length; k++) {
      placeholderNodes[k].setAttribute('placeholder', tr(placeholderNodes[k].getAttribute('data-i18n-placeholder')));
    }
  }

  function clampFontSizePx(px) {
    return Math.min(MAX_FONT_SIZE_PX, Math.max(MIN_FONT_SIZE_PX, px));
  }

  function applyFontSize(px) {
    document.documentElement.style.fontSize = px + 'px';
  }

  // Shared by the locale preference (bilingual-02) and the BL-220 font-size
  // preference below - both need the exact same "read one JSON value from
  // the dashboard's own Cache Storage instance, tolerate it being
  // unavailable/quota'd/missing, fall back to null" shape, differing only
  // in which key and how the raw JSON is validated into a usable value.
  function loadPersistedPreference(key, parseValue) {
    if (!('caches' in window)) {
      return Promise.resolve(null);
    }
    return caches
      .open(PREFERENCES_CACHE_NAME)
      .then(function (cache) {
        return cache.match(key);
      })
      .then(function (res) {
        return res ? res.json() : null;
      })
      .then(parseValue)
      .catch(function () {
        return null;
      });
  }

  // The write half of loadPersistedPreference above - best-effort, never a
  // hard requirement to function: the control still works for this
  // session even when Cache Storage is unavailable/quota'd, it just won't
  // survive a reopen.
  function persistPreference(key, value) {
    if (!('caches' in window)) {
      return;
    }
    caches
      .open(PREFERENCES_CACHE_NAME)
      .then(function (cache) {
        return cache.put(key, new Response(JSON.stringify(value)));
      })
      .catch(function () {});
  }

  function loadPersistedFontSize() {
    return loadPersistedPreference(FONT_SIZE_PREF_KEY, function (data) {
      var px = data && Number(data.fontSizePx);
      return Number.isFinite(px) && px >= MIN_FONT_SIZE_PX && px <= MAX_FONT_SIZE_PX ? px : null;
    });
  }

  function persistFontSize(px) {
    persistPreference(FONT_SIZE_PREF_KEY, { fontSizePx: px });
  }

  // Sets, applies (instantly, no reload), and persists a new font size in
  // one step - the sole entry point A-/A+ use, so clamping always applies.
  function setFontSize(px) {
    currentFontSizePx = clampFontSizePx(px);
    applyFontSize(currentFontSizePx);
    persistFontSize(currentFontSizePx);
  }

  // BL-230: validates against whatever locales are actually configured
  // (window.LOCALES's own keys - the chrome catalog is the one place that
  // already lists them) rather than a hardcoded fr/en pair, so a persisted
  // locale that is no longer configured is ignored instead of trusted.
  function configuredLocales() {
    return (window.LOCALES && Object.keys(window.LOCALES)) || ['en'];
  }

  function loadPersistedLocale() {
    return loadPersistedPreference(LOCALE_PREF_KEY, function (data) {
      return data && configuredLocales().indexOf(data.locale) !== -1 ? data.locale : null;
    });
  }

  function persistLocale(locale) {
    persistPreference(LOCALE_PREF_KEY, { locale: locale });
  }

  // bilingual-02: re-renders chrome + every already-fetched section from
  // its own cached data, instantly, with no reload and no re-fetch.
  function rerenderForLocale() {
    applyChromeLocale();
    if (lastBacklogData) {
      renderAll(lastBacklogData);
    }
    if (docsTree) {
      setDocsAsOfText(docsTree);
      renderDocsExplorer();
    }
    if (recertBatch) {
      setRecertAsOfText(recertBatch);
      renderRecertContent();
    }
  }

  function setLocale(locale) {
    if (locale === currentLocale) {
      return;
    }
    currentLocale = locale;
    persistLocale(locale);
    rerenderForLocale();
  }

  function el(tag, attrs, children) {
    var node = document.createElement(tag);
    if (attrs) {
      for (var k in attrs) {
        node.setAttribute(k, attrs[k]);
      }
    }
    (children || []).forEach(function (c) {
      node.appendChild(typeof c === 'string' ? document.createTextNode(c) : c);
    });
    return node;
  }

  function svgEl(tag, attrs) {
    var node = document.createElementNS(SVG_NS, tag);
    if (attrs) {
      for (var k in attrs) {
        node.setAttribute(k, attrs[k]);
      }
    }
    return node;
  }

  // A minimal, dependency-free bar chart (no charting library - the page
  // must stay self-contained, no CDN, per dashboard-03).
  function barChart(series, width, height) {
    var container = svgEl('svg', { viewBox: '0 0 ' + width + ' ' + height, width: '100%', height: height });
    if (!series || series.length === 0) {
      return container;
    }
    var max = Math.max.apply(
      null,
      series.map(function (p) { return p.value; }).concat([1])
    );
    var barWidth = width / series.length;
    series.forEach(function (p, i) {
      var barHeight = max > 0 ? (p.value / max) * (height - 4) : 0;
      var rect = svgEl('rect', {
        x: i * barWidth + 1,
        y: height - barHeight,
        width: Math.max(1, barWidth - 2),
        height: barHeight,
        fill: '#5fb0ff',
      });
      var title = document.createElementNS(SVG_NS, 'title');
      title.textContent = String(p.periodStart).slice(0, 10) + ': ' + p.value;
      rect.appendChild(title);
      container.appendChild(rect);
    });
    return container;
  }

  function trendArrow(trend) {
    if (!trend || trend.direction === 'unknown') {
      return '';
    }
    if (trend.direction === 'up') {
      return ' ▲';
    }
    if (trend.direction === 'down') {
      return ' ▼';
    }
    return ' ▬';
  }

  // BL-261: true only when a *Fr field is BOTH the one actually being
  // shown right now (the active locale is fr AND that field is present)
  // AND its paired *Untranslated flag says translate.ts degraded to the
  // English fallback (bilingual-05's own "never block publishing"
  // contract) - never flags a field that isn't even being presented as
  // French at the moment. One shared predicate so all four render sites
  // below agree, rather than four separately-drifting copies of this check.
  function isUntranslatedFr(usingFr, untranslatedFlag) {
    return usingFr === true && untranslatedFlag === true;
  }

  function untranslatedNotice() {
    return el('p', { class: 'untranslated-notice' }, [tr('translationUnavailableNotice')]);
  }

  // bilingual-05: a ticket whose title translation is unavailable falls
  // back to its own English title (never blank/undefined) - titleFr is
  // only ever absent when the artifact predates BL-118 or the translation
  // pass hasn't run yet, which must degrade the same way as a flagged
  // failure, not throw.
  // BL-230 scope note: this stays French-only, reading the docs explorer's
  // own docsTree ticket shape (titleFr) - descriptions/docs/scenarios are a
  // later BL-230 slice. Board tickets (backlogDashboard.ts) use the
  // N-locale boardTicketTitle below instead.
  // BL-261: returns a plain string (every caller composes it into a larger
  // line), so an untranslated fallback is labelled INLINE rather than via
  // a separate DOM node - the only shape that fits every call site.
  function ticketTitle(ticket) {
    var usingFr = currentLocale === 'fr' && !!ticket.titleFr;
    if (usingFr) {
      var suffix = isUntranslatedFr(usingFr, ticket.titleFrUntranslated) ? ' (' + tr('translationUnavailableNotice') + ')' : '';
      return ticket.titleFr + suffix;
    }
    return ticket.title;
  }

  // BL-230: the board's own N-locale hook - keyed by whatever locale is
  // active against ticket.titleTranslations (backlogDashboard.ts's
  // per-configured-locale map), so a newly configured target locale needs
  // no change here (add-language-05). Falls back to the authored source
  // title the same way ticketTitle above does: missing/failed translation,
  // or the active locale simply being the source locale, both render the
  // source text rather than nothing.
  function boardTicketTitle(ticket) {
    var translated = ticket.titleTranslations && ticket.titleTranslations[currentLocale];
    if (translated && translated.title) {
      return translated.title;
    }
    return ticket.title;
  }

  function renderTicketList(container, titleKey, tickets) {
    container.appendChild(el('h3', {}, [tr(titleKey) + ' (' + tickets.length + ')']));
    var list = el('ul', {});
    tickets.forEach(function (t) {
      // BL-229: swarm/status badges wrap a raw data enum value (not an
      // English UI label), so they stay unlocalized here and at every
      // other ' [' + x + ']' badge site below - only the surrounding
      // "ETA"/"remaining" words are catalog lookups.
      var badge = t.swarm && t.swarm !== 'primary' ? ' [' + t.swarm + ']' : '';
      var eta = t.p50Iso ? tr('etaPrefix') + t.p50Iso.slice(0, 10) : '';
      list.appendChild(el('li', {}, [t.id + ' — ' + boardTicketTitle(t) + badge + eta]));
    });
    container.appendChild(list);
  }

  // BL-251: read-only - no approve/reject affordance anywhere here.
  // Derived from backlog.json's needsApproval (backlogDashboard.ts's own
  // computeNeedsApproval, sourced from the structured human_approval field
  // only) - this renderer never re-parses a comment itself.
  //
  // BL-266: a needs-approval entry now opens (drill-in, like the docs
  // explorer's own navButton pattern) to a READ-ONLY detail view of that
  // SAME ticket's description + acceptance scenarios, cross-referenced by
  // id into the already-fetched docsTree (BL-117) - no new store, no
  // second Gherkin parser, and never a divergent copy of what the swarm
  // builds against. approvalTicketId (module state, mirrors docsView) is
  // null in list mode; set to a ticket id in detail mode. Approving/
  // rejecting from the phone stays explicitly out of scope (gap #10);
  // this view offers navigation only, never a write action.
  var approvalTicketId = null;

  function findApprovalTicket(id) {
    return docsTree && (docsTree.tickets || []).find(function (t) { return t.id === id; });
  }

  // Pure - the whole description + acceptance-scenario text, in order, as
  // it will be spoken (slice 2). Kept separate from any DOM/adapter code
  // so it is directly exercisable against a fixture ticket object.
  function assembleSpokenText(ticket) {
    var parts = [];
    if (ticket.description) {
      parts.push(ticket.description);
    }
    (ticket.scenarios || []).forEach(function (s) {
      if (s.text) {
        parts.push(s.text);
      }
    });
    return parts.join('\n\n');
  }

  // Pure - BCP-47 language tag SpeechSynthesisUtterance.lang expects,
  // derived from the SAME currentLocale every other section already
  // renders in - never a second, independently-toggled language.
  var SPEECH_LANG_BY_LOCALE = { en: 'en-US', fr: 'fr-FR' };
  function speechLangForLocale(locale) {
    return SPEECH_LANG_BY_LOCALE[locale] || SPEECH_LANG_BY_LOCALE.en;
  }

  // Browser-API boundary (not unit-tested itself, per the testable-module
  // boundary) - on-device only (window.speechSynthesis), no network, no
  // storage; degrades gracefully when unavailable rather than erroring.
  function speechAvailable() {
    return typeof window.speechSynthesis !== 'undefined' && typeof window.SpeechSynthesisUtterance !== 'undefined';
  }

  function renderListenControl(container, ticket) {
    if (!speechAvailable()) {
      container.appendChild(el('p', { class: 'listen-unavailable-note' }, [tr('listenUnavailable')]));
      return;
    }
    var speakingNow = false;
    var btn = el('button', { type: 'button' }, [tr('startListening')]);
    // BL-238 (architect bounce): aria-label mirrors the visible label,
    // matching the existing data-i18n-aria pattern - since this control
    // toggles Listen/Stop, the aria-label must track the SAME state on
    // every transition, not just be set once at creation.
    btn.setAttribute('aria-label', tr('startListening'));
    btn.addEventListener('click', function () {
      if (speakingNow) {
        window.speechSynthesis.cancel();
        speakingNow = false;
        btn.textContent = tr('startListening');
        btn.setAttribute('aria-label', tr('startListening'));
        return;
      }
      window.speechSynthesis.cancel();
      var utterance = new window.SpeechSynthesisUtterance(assembleSpokenText(ticket));
      utterance.lang = speechLangForLocale(currentLocale);
      utterance.onend = function () {
        speakingNow = false;
        btn.textContent = tr('startListening');
        btn.setAttribute('aria-label', tr('startListening'));
      };
      window.speechSynthesis.speak(utterance);
      speakingNow = true;
      btn.textContent = tr('stopListening');
      btn.setAttribute('aria-label', tr('stopListening'));
    });
    container.appendChild(btn);
  }

  function renderApprovalDetail(container, ticketId, entries) {
    var backBtn = el('button', { type: 'button' }, [tr('approvalDetailBack')]);
    backBtn.addEventListener('click', function () {
      if (speechAvailable()) {
        window.speechSynthesis.cancel();
      }
      approvalTicketId = null;
      renderNeedsApproval(entries);
    });
    container.appendChild(backBtn);

    var ticket = findApprovalTicket(ticketId);
    if (!ticket) {
      container.appendChild(noDataParagraph(tr('ticketNotFound')));
      return;
    }
    container.appendChild(el('h3', {}, [ticket.id + ' — ' + ticketTitle(ticket)]));
    var usingFrDescription = currentLocale === 'fr' && !!ticket.descriptionFr;
    var description = usingFrDescription ? ticket.descriptionFr : ticket.description;
    if (isUntranslatedFr(usingFrDescription, ticket.descriptionFrUntranslated)) {
      container.appendChild(untranslatedNotice());
    }
    container.appendChild(el('p', {}, [description || tr('noDescription')]));
    renderListenControl(container, ticket);
    container.appendChild(el('h4', {}, [tr('documentationAcceptance')]));
    if (!ticket.scenarios || ticket.scenarios.length === 0) {
      container.appendChild(noDataParagraph(tr('noScenariosResolved')));
      return;
    }
    ticket.scenarios.forEach(function (s) {
      container.appendChild(el('h5', {}, [s.name]));
      container.appendChild(el('pre', { class: 'gherkin' }, [s.text]));
    });
  }

  function renderNeedsApproval(entries) {
    var container = document.getElementById('needsApproval');
    container.innerHTML = '';
    if (approvalTicketId) {
      renderApprovalDetail(container, approvalTicketId, entries);
      return;
    }
    if (!entries || entries.length === 0) {
      container.appendChild(noDataParagraph(tr('needsApprovalEmpty')));
      return;
    }
    var list = el('ul', {});
    entries.forEach(function (t) {
      var item = el('li', {});
      var btn = el('button', { type: 'button', class: 'docs-list-item' }, [t.id + ' — ' + t.title]);
      btn.addEventListener('click', function () {
        approvalTicketId = t.id;
        renderNeedsApproval(entries);
      });
      item.appendChild(btn);
      list.appendChild(item);
    });
    container.appendChild(list);
  }

  function renderBoard(board) {
    var container = document.getElementById('board');
    container.innerHTML = '';
    renderTicketList(container, 'boardActive', board.active);
    renderTicketList(container, 'boardPaused', board.paused);

    container.appendChild(el('h3', {}, [tr('boardDoneByMilestone')]));
    var milestones = Object.keys(board.doneByMilestone).sort();
    var doneList = el('ul', {});
    milestones.forEach(function (m) {
      doneList.appendChild(el('li', {}, [m + ': ' + board.doneByMilestone[m].length]));
    });
    container.appendChild(doneList);
  }

  function renderVelocity(velocity) {
    var container = document.getElementById('velocity');
    container.innerHTML = '';
    container.appendChild(
      el('p', {}, ['Trailing ' + velocity.rollingWindowDays + 'd: ' + velocity.rollingWindowCount + ' closed' + trendArrow(velocity.trend)])
    );
    container.appendChild(barChart(velocity.weeklySeries, 300, 80));
  }

  // BL-228: reuses the SAME forecast computeForecasts already produces (no
  // parallel ETA model) - forecasts.milestones already drives the
  // per-ticket ETAs on the board (ticketTitle/eta above), this just
  // surfaces the same p50/p85 per milestone here too.
  function milestoneEtaSuffix(forecasts, milestoneName) {
    var forecast = ((forecasts && forecasts.milestones) || []).filter(function (f) {
      return f.milestone === milestoneName;
    })[0];
    if (!forecast || !forecast.p50Iso) {
      return ' — ' + tr('noEtaYet');
    }
    var text = tr('etaPrefix') + forecast.p50Iso.slice(0, 10);
    if (forecast.p85Iso) {
      text += tr('p85RangeInfix') + forecast.p85Iso.slice(0, 10) + ')';
    }
    return text;
  }

  // The overall "all remaining work" ETA: the latest projected completion
  // (max p50) across every open ticket's own forecast - not a new model,
  // just the max of the same per-ticket forecasts.tickets p50s.
  function overallEtaText(forecasts) {
    var p50Dates = ((forecasts && forecasts.tickets) || [])
      .map(function (t) { return t.p50Iso; })
      .filter(function (d) { return d; });
    if (p50Dates.length === 0) {
      return tr('noEtaYet');
    }
    var maxDate = p50Dates.reduce(function (max, d) { return d > max ? d : max; });
    return tr('overallEtaPrefix') + maxDate.slice(0, 10);
  }

  function renderBurndown(burndown, forecasts) {
    var container = document.getElementById('burndown');
    container.innerHTML = '';
    if (!burndown || burndown.length === 0) {
      container.appendChild(el('p', {}, [tr('burndownNoMilestones')]));
      return;
    }
    container.appendChild(el('p', { class: 'burndown-overall-eta' }, [overallEtaText(forecasts)]));
    burndown.forEach(function (m) {
      container.appendChild(el('h4', {}, [m.milestone + ': ' + m.currentRemaining + tr('remainingSuffix') + milestoneEtaSuffix(forecasts, m.milestone) + trendArrow(m.trend)]));
      container.appendChild(barChart(m.dailySeries, 300, 60));
    });
  }

  function renderCycleTime(cycleTime) {
    var container = document.getElementById('cycleTime');
    container.innerHTML = '';
    if (cycleTime.medianMs === null) {
      container.appendChild(el('p', {}, [tr('cycleTimeNoTickets')]));
      return;
    }
    var medianH = Math.round(cycleTime.medianMs / 3600000);
    var p85H = Math.round(cycleTime.p85Ms / 3600000);
    container.appendChild(
      el('p', {}, ['Median ' + medianH + 'h, p85 ' + p85H + 'h over ' + cycleTime.sampleCount + ' ticket(s)' + trendArrow(cycleTime.trend)])
    );
  }

  // BL-213 cost-06b: the card is hidden entirely (not rendered empty) when
  // backlog.json carries no costHealth field - the field's own presence is
  // the signal, nothing here guesses at "no data yet" vs "not shipped yet".
  function renderCostHealth(costHealth) {
    var section = document.getElementById('costHealthSection');
    var container = document.getElementById('costHealth');
    if (!costHealth) {
      section.style.display = 'none';
      return;
    }
    section.style.display = '';
    container.innerHTML = '';

    var agentsList = el('ul', {});
    (costHealth.agents || []).forEach(function (a) {
      var costText = a.costUsd !== null ? '$' + a.costUsd.value.toFixed(2) + trendArrow(a.costUsd.trend) : 'no priced usage';
      agentsList.appendChild(el('li', {}, [a.role + ': ' + a.tokens.value + ' tokens' + trendArrow(a.tokens.trend) + ', ' + costText]));
    });
    container.appendChild(el('h4', {}, [tr('costHealthAgentTokens')]));
    container.appendChild(agentsList);

    if (costHealth.topExpensiveTickets && costHealth.topExpensiveTickets.length > 0) {
      container.appendChild(el('h4', {}, [tr('costHealthTopExpensive')]));
      var ticketsList = el('ul', {});
      costHealth.topExpensiveTickets.forEach(function (t) {
        ticketsList.appendChild(el('li', {}, [t.ticketId + ': $' + t.costUsd.toFixed(2)]));
      });
      container.appendChild(ticketsList);
    }

    var flow = costHealth.flowBalance;
    container.appendChild(el('p', {}, [
      'Flow balance: specced ' + flow.speccedPerDay.value + '/day' + trendArrow(flow.speccedPerDay.trend) +
      ', closed ' + flow.closedPerDay.value + '/day' + trendArrow(flow.closedPerDay.trend),
    ]));

    var rel = costHealth.reliability;
    container.appendChild(el('p', {}, [
      'Reliability: ' + rel.chases.value + ' chases' + trendArrow(rel.chases.trend) +
      ', ' + rel.nudges.value + ' nudges' + trendArrow(rel.nudges.trend) +
      ', ' + rel.respawns.value + ' respawns' + trendArrow(rel.respawns.trend) +
      ', ' + rel.failedDeliveries.value + ' failed deliveries' + trendArrow(rel.failedDeliveries.trend),
    ]));

    if (costHealth.resourceAnomalies && costHealth.resourceAnomalies.length > 0) {
      container.appendChild(el('h4', {}, [tr('costHealthResourceAnomalies')]));
      var anomaliesList = el('ul', {});
      costHealth.resourceAnomalies.forEach(function (a) {
        var mb = Math.round(a.rssBytes / (1024 * 1024));
        anomaliesList.appendChild(el('li', {}, [a.role + ': ' + mb + 'MB' + trendArrow(a.rssTrend) + ', ' + a.cpuPercent.toFixed(1) + '% cpu' + trendArrow(a.cpuTrend)]));
      });
      container.appendChild(anomaliesList);
    }
  }

  function renderAll(data) {
    lastBacklogData = data;
    var asOf = document.getElementById('asOf');
    var shaText = data.sourceSha ? ' (' + data.sourceSha.slice(0, 10) + ')' : '';
    asOf.textContent = tr('asOfPrefix') + new Date(data.generatedAtIso).toLocaleString() + shaText;
    renderNeedsApproval(data.needsApproval);
    renderBoard(data.board);
    renderVelocity(data.metrics.velocity);
    renderBurndown(data.metrics.burndown, data.metrics.forecasts);
    renderCycleTime(data.metrics.cycleTime);
    renderCostHealth(data.costHealth || null);
  }

  // BL-117: read-only documentation drill-down (vision -> milestone ->
  // ticket -> Gherkin). No affordance anywhere in this explorer edits
  // documentation or creates/modifies tickets (docs-drilldown-05) - every
  // control below only ever navigates docsView and re-renders from the
  // already-fetched docsTree, never writes anything back to the network.
  var docsTree = null;
  var docsView = { level: 'root' };
  var docsSearchQuery = '';

  // BL-254: pure, client-side full-text search filter, mirroring
  // extension/src/docs/docsTree.ts's filterDocsTree exactly (case-
  // insensitive substring over a ticket's title/description/scenario
  // text, pruning to matching tickets while keeping the milestone
  // hierarchy). Duplicated here because this file is a plain, unbundled
  // browser script with no access to the compiled TS module - the two
  // must be kept in sync by hand; the TS version is the one unit- and
  // acceptance-tested, this one is exercised by pwaDocsExplorer.test.js.
  function ticketMatchesQuery(ticket, lowerQuery) {
    if (ticket.title && ticket.title.toLowerCase().indexOf(lowerQuery) !== -1) {
      return true;
    }
    if (ticket.description && ticket.description.toLowerCase().indexOf(lowerQuery) !== -1) {
      return true;
    }
    return (ticket.scenarios || []).some(function (s) { return s.text.toLowerCase().indexOf(lowerQuery) !== -1; });
  }

  function filterDocsTree(tree, query) {
    var trimmed = (query || '').trim();
    if (!trimmed) {
      return tree;
    }
    var lowerQuery = trimmed.toLowerCase();
    var tickets = (tree.tickets || []).filter(function (t) { return ticketMatchesQuery(t, lowerQuery); });
    var matchingIds = {};
    tickets.forEach(function (t) { matchingIds[t.id] = true; });
    var milestones = (tree.milestones || [])
      .map(function (m) { return { milestone: m.milestone, tickets: m.tickets.filter(function (t) { return matchingIds[t.id]; }) }; })
      .filter(function (m) { return m.tickets.length > 0; });
    var filtered = {};
    for (var key in tree) {
      if (Object.prototype.hasOwnProperty.call(tree, key)) {
        filtered[key] = tree[key];
      }
    }
    filtered.tickets = tickets;
    filtered.milestones = milestones;
    return filtered;
  }

  // The filtered view every list-rendering function below reads from -
  // vision docs are never filtered (search is over tickets/Gherkin only).
  function activeDocsTree() {
    return filterDocsTree(docsTree, docsSearchQuery);
  }

  function findMilestone(name) {
    return (activeDocsTree().milestones || []).find(function (m) { return m.milestone === name; });
  }

  function findTicket(id) {
    return (activeDocsTree().tickets || []).find(function (t) { return t.id === id; });
  }

  function findVisionDoc(id) {
    return (docsTree.vision || []).find(function (v) { return v.id === id; });
  }

  function navButton(label, view, extraClass) {
    var className = extraClass ? 'docs-list-item ' + extraClass : 'docs-list-item';
    var btn = el('button', { type: 'button', class: className }, [label]);
    btn.addEventListener('click', function () {
      docsView = view;
      renderDocsExplorer();
    });
    return btn;
  }

  // BL-253: whole-ticket implementation status, read directly off the tree
  // data's own implemented flag (docsTree.ts computes it once) - never
  // re-derived from status here, so the PWA can never drift from the
  // done/not-done rule the tree already applied. Greying is visual only:
  // the returned label/class never disable anything, they only decorate.
  function implementationLabel(t) {
    return t.implemented ? tr('implementedLabel') : tr('notYetImplementedLabel');
  }

  function implementationClass(t) {
    return t.implemented ? '' : 'not-yet-implemented';
  }

  function renderDocsCrumbs() {
    var container = document.getElementById('docsCrumbs');
    container.innerHTML = '';
    var crumbs = [{ label: tr('documentationRoot'), view: { level: 'root' } }];
    if (docsView.level === 'vision') {
      var doc = findVisionDoc(docsView.docId);
      crumbs.push({ label: doc ? doc.title : docsView.docId, view: docsView });
    } else if (docsView.level === 'milestone' || docsView.level === 'ticket' || docsView.level === 'scenario') {
      crumbs.push({ label: docsView.milestone, view: { level: 'milestone', milestone: docsView.milestone } });
    }
    if (docsView.level === 'ticket' || docsView.level === 'scenario') {
      crumbs.push({ label: docsView.ticketId, view: { level: 'ticket', milestone: docsView.milestone, ticketId: docsView.ticketId } });
    }
    if (docsView.level === 'scenario') {
      var ticket = findTicket(docsView.ticketId);
      var scenario = ticket && ticket.scenarios[docsView.scenarioIndex];
      crumbs.push({ label: scenario ? scenario.name : 'scenario', view: docsView });
    }
    crumbs.forEach(function (crumb, i) {
      if (i > 0) {
        container.appendChild(document.createTextNode(' › '));
      }
      var isCurrent = i === crumbs.length - 1;
      if (isCurrent) {
        container.appendChild(el('strong', {}, [crumb.label]));
        return;
      }
      var link = el('button', { type: 'button' }, [crumb.label]);
      link.addEventListener('click', function () {
        docsView = crumb.view;
        renderDocsExplorer();
      });
      container.appendChild(link);
    });
  }

  function renderDocsRoot(container) {
    container.appendChild(el('h3', {}, [tr('documentationVision')]));
    (docsTree.vision || []).forEach(function (doc) {
      container.appendChild(navButton(doc.title, { level: 'vision', docId: doc.id }));
    });
    container.appendChild(el('h3', {}, [tr('documentationMilestones')]));
    var tree = activeDocsTree();
    if (docsSearchQuery.trim() && tree.tickets.length === 0) {
      container.appendChild(noDataParagraph(tr('docsNoSearchResults')));
      return;
    }
    (tree.milestones || []).forEach(function (m) {
      container.appendChild(navButton(m.milestone + ' (' + m.tickets.length + ')', { level: 'milestone', milestone: m.milestone }));
    });
  }

  // bilingual-03: a markdown vision doc renders contentFr in FR mode,
  // falling back to English content when no translation is available yet
  // (bilingual-05) - a mermaid doc's content is a diagram source and never
  // gains a contentFr field at all (bilingual-06), so it always renders
  // its one and only content value regardless of locale.
  function renderDocsVision(container) {
    var doc = findVisionDoc(docsView.docId);
    if (!doc) {
      container.appendChild(noDataParagraph(tr('documentationNotFound')));
      return;
    }
    var usingFr = currentLocale === 'fr' && !!doc.contentFr;
    var text = usingFr ? doc.contentFr : doc.content;
    if (isUntranslatedFr(usingFr, doc.contentFrUntranslated)) {
      container.appendChild(untranslatedNotice());
    }
    container.appendChild(el('pre', { class: 'doc-content' }, [text]));
  }

  function renderDocsMilestone(container) {
    var milestone = findMilestone(docsView.milestone);
    if (!milestone) {
      container.appendChild(noDataParagraph(tr('milestoneNotFound')));
      return;
    }
    milestone.tickets.forEach(function (t) {
      container.appendChild(navButton(
        t.id + ' — ' + ticketTitle(t) + ' [' + t.status + '] (' + implementationLabel(t) + ')',
        { level: 'ticket', milestone: docsView.milestone, ticketId: t.id },
        implementationClass(t)
      ));
    });
  }

  function renderDocsTicket(container) {
    var ticket = findTicket(docsView.ticketId);
    if (!ticket) {
      container.appendChild(noDataParagraph(tr('ticketNotFound')));
      return;
    }
    var usingFrDescription = currentLocale === 'fr' && !!ticket.descriptionFr;
    var description = usingFrDescription ? ticket.descriptionFr : ticket.description;
    var statusLine = el('p', { class: implementationClass(ticket) }, [
      ticketTitle(ticket) + ' [' + ticket.status + '] (' + implementationLabel(ticket) + ')' + (ticket.priority !== undefined ? ' priority ' + ticket.priority : ''),
    ]);
    container.appendChild(statusLine);
    if (isUntranslatedFr(usingFrDescription, ticket.descriptionFrUntranslated)) {
      container.appendChild(untranslatedNotice());
    }
    container.appendChild(el('p', {}, [description || tr('noDescription')]));
    container.appendChild(el('h4', {}, [tr('documentationAcceptance')]));
    if (!ticket.scenarios || ticket.scenarios.length === 0) {
      container.appendChild(noDataParagraph(tr('noScenariosResolved')));
      return;
    }
    ticket.scenarios.forEach(function (s, i) {
      container.appendChild(navButton(s.name, { level: 'scenario', milestone: docsView.milestone, ticketId: docsView.ticketId, scenarioIndex: i }));
    });
  }

  // bilingual-04: the scenario text itself is ALWAYS canonical English,
  // regardless of currentLocale - it is the binding acceptance contract,
  // never swapped for textFr. A French rendering is available only via an
  // explicit one-tap reveal, hidden until tapped, and never presented as
  // if it were the contract itself.
  function renderDocsScenario(container) {
    var ticket = findTicket(docsView.ticketId);
    var scenario = ticket && ticket.scenarios[docsView.scenarioIndex];
    if (!scenario) {
      container.appendChild(noDataParagraph(tr('scenarioNotFound')));
      return;
    }
    container.appendChild(el('pre', { class: 'gherkin' }, [scenario.text]));
    if (scenario.textFr) {
      var revealed = false;
      // BL-261: reveal semantics don't gate on currentLocale at all
      // (bilingual-04's own design - available regardless of locale
      // toggle), so "using" the French rendering is simply "has it been
      // revealed" rather than a locale check.
      var flagged = isUntranslatedFr(true, scenario.textFrUntranslated);
      var notice = flagged ? untranslatedNotice() : null;
      if (notice) {
        notice.style.display = 'none';
      }
      var frBlock = el('pre', { class: 'gherkin french-reveal' }, [scenario.textFr]);
      frBlock.style.display = 'none';
      var revealBtn = el('button', { type: 'button' }, [tr('showFrenchScenario')]);
      revealBtn.addEventListener('click', function () {
        revealed = !revealed;
        frBlock.style.display = revealed ? '' : 'none';
        if (notice) {
          notice.style.display = revealed ? '' : 'none';
        }
        revealBtn.textContent = tr(revealed ? 'hideFrenchScenario' : 'showFrenchScenario');
      });
      container.appendChild(revealBtn);
      if (notice) {
        container.appendChild(notice);
      }
      container.appendChild(frBlock);
    }
  }

  function renderDocsExplorer() {
    var container = document.getElementById('docsExplorer');
    container.innerHTML = '';
    if (!docsTree) {
      container.appendChild(noDataParagraph(tr('docsNotAvailable')));
      return;
    }
    renderDocsCrumbs();
    if (docsView.level === 'vision') {
      renderDocsVision(container);
    } else if (docsView.level === 'milestone') {
      renderDocsMilestone(container);
    } else if (docsView.level === 'ticket') {
      renderDocsTicket(container);
    } else if (docsView.level === 'scenario') {
      renderDocsScenario(container);
    } else {
      renderDocsRoot(container);
    }
  }

  function noDataParagraph(text) {
    return el('p', {}, [text || 'no data']);
  }

  // BL-117 docs-drilldown-04: labeled with the commit/timestamp it was
  // rendered from, same honesty requirement as the backlog board. Split
  // out of renderDocsTree so a locale toggle can re-set it (via
  // rerenderForLocale) without re-fetching/re-assigning docsTree itself.
  function setDocsAsOfText(data) {
    var asOf = document.getElementById('docsAsOf');
    var shaText = data.sourceSha ? ' (' + data.sourceSha.slice(0, 10) + ')' : '';
    asOf.textContent = tr('asOfPrefix') + new Date(data.generatedAtIso).toLocaleString() + shaText;
  }

  function renderDocsTree(data) {
    docsTree = data;
    setDocsAsOfText(data);
    renderDocsExplorer();
  }

  // BL-150: recertification - a separate section from the read-only docs
  // explorer above (which keeps its own docs-drilldown-05 "no edit
  // affordance anywhere" guarantee unchanged). The PWA is fully static
  // (published to GitHub Pages, no live backend it can reach), so every
  // outcome (confirm/update/delete) leaves the phone the same way: a
  // mailto: link the human taps, matching extension/src/docs/recertification.ts's
  // buildRecertEmailSubject/buildRecertEmailBody exactly so the extension
  // host's inbound parser understands it.
  var recertBatch = null;

  function recertEmailSubject(scenarioId, outcome) {
    return 'SwarmForge recert: ' + outcome + ' ' + scenarioId;
  }

  function recertEmailBody(scenarioId, outcome, newText) {
    var lines = ['scenario: ' + scenarioId, 'outcome: ' + outcome];
    if (outcome === 'update') {
      lines.push('---', newText || '');
    }
    return lines.join('\n');
  }

  function recertEmailTo() {
    return (recertBatch && recertBatch.recertEmailTo) || RECERT_EMAIL_FALLBACK;
  }

  function recertMailtoHref(scenarioId, outcome, newText) {
    var subject = recertEmailSubject(scenarioId, outcome);
    var body = recertEmailBody(scenarioId, outcome, newText);
    return 'mailto:' + encodeURIComponent(recertEmailTo()) + '?subject=' + encodeURIComponent(subject) + '&body=' + encodeURIComponent(body);
  }

  // BL-238: role="button" on an <a href> promises Space-bar activation per
  // ARIA button semantics, but a native anchor only activates on Enter/
  // click - this keydown handler completes that contract rather than
  // leaving Space silently do nothing for a keyboard/screen-reader user.
  function mailtoLink(label, href) {
    var link = el('a', { href: href, class: 'recert-send-link', role: 'button' }, [label]);
    link.addEventListener('keydown', function (e) {
      if (e.key === ' ') {
        e.preventDefault();
        link.click();
      }
    });
    return link;
  }

  function renderRecertUpdateForm(container, scenario) {
    container.innerHTML = '';
    container.appendChild(el('h4', {}, [scenario.name]));
    // BL-238: the preceding <h4> is not programmatically associated with
    // this control (no <label for>/id pairing in this codebase's plain-DOM
    // helper style) - aria-label gives it an accessible name directly.
    var textarea = el('textarea', { class: 'recert-update-text', 'aria-label': 'Edit scenario text: ' + scenario.name }, []);
    textarea.value = scenario.text;
    container.appendChild(textarea);

    var actions = el('div', { class: 'recert-actions' }, []);
    var sendLink = mailtoLink(tr('recertSendUpdate'), recertMailtoHref(scenario.id, 'update', textarea.value));
    // the mailto: href must reflect whatever the human has actually typed
    // by the time they tap it, not just the text the form opened with.
    textarea.addEventListener('input', function () {
      sendLink.setAttribute('href', recertMailtoHref(scenario.id, 'update', textarea.value));
    });
    actions.appendChild(sendLink);
    var cancelBtn = el('button', { type: 'button' }, [tr('recertCancel')]);
    cancelBtn.addEventListener('click', renderRecertContent);
    actions.appendChild(cancelBtn);
    container.appendChild(actions);
  }

  // recert-04: delete is a double gate on top of the specifier's own
  // proposal review - this in-app confirmation step is separate from, and
  // must precede, the mailto: compose itself. The "Yes, delete" link's
  // href (and so its ability to actually send anything) only exists once
  // this confirmation screen is showing; cancelling returns to the normal
  // confirm/update/delete choice with nothing sent.
  function renderRecertDeleteConfirm(container, scenario) {
    container.innerHTML = '';
    container.appendChild(el('h4', {}, [scenario.name]));
    container.appendChild(el('p', { class: 'recert-delete-warning' }, [tr('recertDeleteWarning')]));

    var actions = el('div', { class: 'recert-actions' }, []);
    actions.appendChild(mailtoLink(tr('recertYesDelete'), recertMailtoHref(scenario.id, 'delete')));
    var cancelBtn = el('button', { type: 'button' }, [tr('recertCancel')]);
    cancelBtn.addEventListener('click', renderRecertContent);
    actions.appendChild(cancelBtn);
    container.appendChild(actions);
  }

  function renderRecertContent() {
    var container = document.getElementById('recertContent');
    container.innerHTML = '';
    if (!recertBatch || !recertBatch.batch || recertBatch.batch.length === 0) {
      container.appendChild(noDataParagraph(tr('recertNoneNeeded')));
      return;
    }
    var scenario = recertBatch.batch[0];
    container.appendChild(el('h4', {}, [scenario.name]));
    container.appendChild(el('pre', { class: 'gherkin' }, [scenario.text]));

    var actions = el('div', { class: 'recert-actions' }, []);
    actions.appendChild(mailtoLink(tr('recertConfirm'), recertMailtoHref(scenario.id, 'confirm')));

    var updateBtn = el('button', { type: 'button' }, [tr('recertUpdate')]);
    updateBtn.addEventListener('click', function () {
      renderRecertUpdateForm(container, scenario);
    });
    actions.appendChild(updateBtn);

    var deleteBtn = el('button', { type: 'button' }, [tr('recertDelete')]);
    deleteBtn.addEventListener('click', function () {
      renderRecertDeleteConfirm(container, scenario);
    });
    actions.appendChild(deleteBtn);

    container.appendChild(actions);
  }

  function setRecertAsOfText(data) {
    var asOf = document.getElementById('recertAsOf');
    asOf.textContent = tr('asOfPrefix') + new Date(data.generatedAtIso).toLocaleString();
  }

  function renderRecertBatch(data) {
    recertBatch = data;
    setRecertAsOfText(data);
    renderRecertContent();
  }

  function registerServiceWorker() {
    if (!('serviceWorker' in navigator)) {
      return Promise.resolve(null);
    }
    return navigator.serviceWorker.register('./sw.js').catch(function () {
      return null;
    });
  }

  // BL-097 dashboard-06/07: Periodic Background Sync is Android/Chrome-only
  // and requires the PWA to be installed with the permission granted -
  // every step here is feature-detected so an unsupported browser
  // (dashboard-07) never sees an error or a permission prompt it can't
  // satisfy; freshness there is just open-time fetch plus whatever the
  // service worker already caches.
  function registerPeriodicSync(registration) {
    if (!registration || !('periodicSync' in registration) || !('permissions' in navigator)) {
      return;
    }
    navigator.permissions
      .query({ name: 'periodic-background-sync' })
      .then(function (status) {
        if (status.state !== 'granted') {
          return;
        }
        return registration.periodicSync.register('refresh-backlog-json', { minInterval: 2 * 60 * 60 * 1000 });
      })
      .catch(function () {
        // Unsupported permission name, or registration rejected (e.g. the
        // browser's own site-engagement heuristics aren't met yet) - silent,
        // per dashboard-07's "no error or prompt" requirement.
      });
  }

  // bilingual-01: applied immediately, before the persisted-locale lookup
  // below resolves, so the very first paint is always English chrome -
  // never derived from navigator.language.
  applyChromeLocale();

  // BL-230: cycles through every configured locale (window.LOCALES's own
  // keys), not a hardcoded en/fr flip - with today's two configured
  // locales this is identical to the old toggle; adding a third locale to
  // the catalog is then a config change only, the click handler itself
  // never changes (add-language-05).
  function nextLocale() {
    var locales = configuredLocales();
    var idx = locales.indexOf(currentLocale);
    return locales[(idx + 1 + locales.length) % locales.length];
  }

  var localeToggleButton = document.getElementById('localeToggle');
  if (localeToggleButton) {
    localeToggleButton.addEventListener('click', function () {
      setLocale(nextLocale());
    });
  }

  // bilingual-02: a previously-toggled locale (persisted via Cache Storage,
  // not localStorage) is restored on reopen. A fresh device/first launch
  // resolves to null here and simply stays on the English default applied
  // above.
  loadPersistedLocale().then(function (persisted) {
    if (persisted) {
      currentLocale = persisted;
      rerenderForLocale();
    }
  });

  // BL-220 default-large-01: applied immediately, before the persisted
  // font-size lookup below resolves, so the very first paint is always the
  // large default - a fresh device/first launch simply stays here.
  applyFontSize(currentFontSizePx);

  var fontDecreaseButton = document.getElementById('fontDecrease');
  if (fontDecreaseButton) {
    fontDecreaseButton.addEventListener('click', function () {
      setFontSize(currentFontSizePx - FONT_SIZE_STEP_PX);
    });
  }
  var fontIncreaseButton = document.getElementById('fontIncrease');
  if (fontIncreaseButton) {
    fontIncreaseButton.addEventListener('click', function () {
      setFontSize(currentFontSizePx + FONT_SIZE_STEP_PX);
    });
  }

  // BL-220 persist-04: a previously-chosen size (persisted via the same
  // Cache Storage instance as the locale preference) is restored on
  // reopen. A fresh device/first launch resolves to null here and simply
  // stays on the default applied above.
  loadPersistedFontSize().then(function (persisted) {
    if (persisted !== null) {
      currentFontSizePx = persisted;
      applyFontSize(persisted);
    }
  });

  // BL-254: the search box lives once in static markup (never re-created
  // by renderDocsExplorer's own container.innerHTML reset), so typing
  // never loses focus/cursor position across re-renders.
  var docsSearchInput = document.getElementById('docsSearchInput');
  if (docsSearchInput) {
    docsSearchInput.addEventListener('input', function () {
      docsSearchQuery = docsSearchInput.value;
      renderDocsExplorer();
    });
  }

  fetch(DASHBOARD_URL)
    .then(function (res) {
      return res.json();
    })
    .then(renderAll)
    .catch(function () {
      document.getElementById('asOf').textContent = tr('couldNotLoadBacklog');
    });

  fetch(DOCS_TREE_URL)
    .then(function (res) {
      return res.json();
    })
    .then(renderDocsTree)
    .catch(function () {
      document.getElementById('docsAsOf').textContent = tr('couldNotLoadDocsTree');
    });

  fetch(RECERT_BATCH_URL)
    .then(function (res) {
      return res.json();
    })
    .then(renderRecertBatch)
    .catch(function () {
      document.getElementById('recertAsOf').textContent = tr('couldNotLoadRecertBatch');
    });

  registerServiceWorker().then(registerPeriodicSync);
})();
