#!/usr/bin/env bash
# BL-101: generates the systemd unit for a headless secondary swarm host
# (Pi 5 / VPS) - launches at boot, and stops cleanly via the existing
# ./swarm-kill path (not a bespoke teardown) on `systemctl stop` or shutdown.
#
# The GitHub Actions self-hosted runner gets its OWN unit from its own
# installer (./svc.sh install, documented in the bring-up runbook) rather
# than a hand-authored one here - actions/runner ships and maintains that
# unit itself, and duplicating it would drift from upstream's own service
# definition as that project changes.
#
# Usage: generate_systemd_units.sh <project-root> <pack-name> <linux-user> [output-path]
#   project-root: absolute path to the cloned repo on this box
#   pack-name:    the --pack argument ./swarm launches with (e.g. second-swarm,
#                 or a per-host conf generated by generate_secondary_conf.sh)
#   linux-user:   the non-root user the swarm runs as
#   output-path:  where to write the unit; defaults to stdout
#
# BL-101 VIOLATION (architect): a systemd service starts with a clean
# environment - it does NOT source the launching user's shell profile. Env
# vars an operator exports there (CLAUDE_CODE_OAUTH_TOKEN for the Option B
# headless-auth path in the runbook) would silently never reach the swarm
# process under systemd. EnvironmentFile= is the standard systemd mechanism
# for this: a root-owned, restricted-permission file outside the repo clone
# (matches the runbook's own "secrets never inside the repo clone" posture).
# The leading '-' tolerates the file being absent (Option A/interactive-auth
# operators need no such file, and the unit must not fail to start over it).

set -euo pipefail

PROJECT_ROOT="${1:?Usage: generate_systemd_units.sh <project-root> <pack-name> <linux-user> [output-path]}"
PACK_NAME="${2:?Usage: generate_systemd_units.sh <project-root> <pack-name> <linux-user> [output-path]}"
LINUX_USER="${3:?Usage: generate_systemd_units.sh <project-root> <pack-name> <linux-user> [output-path]}"
OUTPUT_PATH="${4:-}"

if [[ "$PROJECT_ROOT" != /* ]]; then
  echo "generate_systemd_units.sh: project-root must be an absolute path, got: $PROJECT_ROOT" >&2
  exit 1
fi

ENV_FILE="/etc/swarmforge/${PACK_NAME}.env"

UNIT="$(cat <<EOF
[Unit]
Description=SwarmForge secondary swarm ($PACK_NAME)
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
User=$LINUX_USER
WorkingDirectory=$PROJECT_ROOT
Environment=SWARMFORGE_TERMINAL=none
EnvironmentFile=-$ENV_FILE
ExecStart=$PROJECT_ROOT/swarm $PROJECT_ROOT --pack $PACK_NAME
ExecStop=$PROJECT_ROOT/swarm-kill
TimeoutStartSec=120

[Install]
WantedBy=multi-user.target
EOF
)"

if [[ -n "$OUTPUT_PATH" ]]; then
  printf '%s\n' "$UNIT" > "$OUTPUT_PATH"
else
  printf '%s\n' "$UNIT"
fi
