#!/usr/bin/env bash
# BL-101: generates the systemd unit for a headless secondary swarm host
# (Pi 5 / VPS) - launches at boot, and stops cleanly via the existing
# ./swarm-kill path (not a bespoke teardown) on `systemctl stop` or shutdown.
#
# The GitHub Actions self-hosted runner gets its OWN unit from its own
# installer (./svc.sh install, documented in the bring-up runbook) rather
# than a hand-authored one here - actions/runner ships and maintains that
# unit itself, and duplicating it would drift from upstream's own service
# definition as that project changes.
#
# BL-304: also renders the OPERATOR-RUNTIME unit (--unit=operator) - a
# crash/OOM/reboot previously left operator_runtime.bb dead with nothing to
# respawn it (autostart was manual/external). systemd is the supervisor
# (Restart=always, boot-enabled, StartLimitIntervalSec=0 in [Unit] so a
# crash burst never permanently stops the unit - the exact analogue of the
# BL-303 sticky-give-up defect fixed at the front-desk-supervisor layer).
#
# BL-366: none of the rendered units could actually start. ExecStart=bb ...
# named a bare command - systemd does not search PATH for ExecStart, so
# every start failed ("Command bb is not executable"). StartLimitIntervalSec
# was rendered into [Service], where systemd v230+ silently discards it -
# the crash-burst guard above was decorative. Fixed by resolving bb's
# absolute path at generate time (this script runs ON the target host - see
# provision_secondary_host.sh), moving StartLimitIntervalSec to [Unit] on
# all three units, and adding an Environment=PATH= (systemd's own minimal
# PATH excludes ~/.local/bin) so the scripts these units launch can find
# bb/node/claude too. systemd-analyze verify now gates every rendered unit
# in test_generate_systemd_units.sh - the check that would have caught both
# defects in one second.
#
# BL-351: also renders the FRONT-DESK unit (--unit=front-desk) - the
# bridge + Telegram bot, the human's entire phone-card/holistic-UI/
# Concierge/Telegram surface, had NO boot unit at all (BL-336 findings
# G1/G2): a reboot silently took it down with nothing to bring it back.
# Reuses launch_front_desk.sh's OWN idempotent already-running guard and
# front_desk_supervisor.bb's OWN bounded-restart supervision of the
# bridge/bot pair - this unit's only job is making the SUPERVISOR itself
# boot-persistent and restart-on-death, the same relationship the `swarm`
# unit has to handoffd_supervisor.bb.
#
# Type=forking (not Type=simple like operator): launch_front_desk.sh is a
# LAUNCHER - it forks front_desk_supervisor.bb into the background via
# nohup, waits for it to claim its own pid file, then EXITS. Type=simple
# would track launch_front_desk.sh's own (near-immediate) exit as "the
# service stopped", making Restart=always relaunch the launcher in a tight
# loop instead of ever tracking the actual supervisor. Type=forking +
# PIDFile= is systemd's standard idiom for exactly this launcher-forks-
# and-exits shape: it waits for ExecStart to exit, then tracks whatever
# pid PIDFile names for the unit's actual lifetime - so Restart=always
# correctly fires only if the SUPERVISOR itself dies, and re-running
# launch_front_desk.sh's own idempotent guard means "systemctl start" against
# an already-running (e.g. hand-launched) front desk is a safe no-op, not a
# second instance (front-desk-survives-reboot-05).
#
# Usage: generate_systemd_units.sh <project-root> <pack-name> <linux-user> [output-path] [--unit=swarm|operator|front-desk]
#   project-root: absolute path to the cloned repo on this box
#   pack-name:    the --pack argument ./swarm launches with (e.g. second-swarm,
#                 or a per-host conf generated by generate_secondary_conf.sh) -
#                 also the operator/front-desk units' own per-host name/env-file key
#   linux-user:   the non-root user the swarm/runtime runs as
#   output-path:  where to write the unit; defaults to stdout
#   --unit=       which unit to render: "swarm" (default), "operator", or
#                 "front-desk" - parsed out of the argument list regardless
#                 of position, so every existing 3/4-positional-arg call
#                 site (no --unit= flag at all) keeps rendering the swarm
#                 unit unchanged.
#
# BL-101 VIOLATION (architect): a systemd service starts with a clean
# environment - it does NOT source the launching user's shell profile. Env
# vars an operator exports there (CLAUDE_CODE_OAUTH_TOKEN for the Option B
# headless-auth path in the runbook) would silently never reach the swarm
# process under systemd. EnvironmentFile= is the standard systemd mechanism
# for this: a root-owned, restricted-permission file outside the repo clone
# (matches the runbook's own "secrets never inside the repo clone" posture).
# The leading '-' tolerates the file being absent (Option A/interactive-auth
# operators need no such file, and the unit must not fail to start over it).
# BL-304 reuses this SAME per-pack env file for the operator unit - the
# runtime AND the disposable LLM it launches (CLAUDE_CODE_OAUTH_TOKEN) need
# the identical secrets the swarm process does, on the same host.

set -euo pipefail

UNIT_TYPE="swarm"
POSITIONAL=()
for arg in "$@"; do
  if [[ "$arg" == "--unit="* ]]; then
    UNIT_TYPE="${arg#--unit=}"
  else
    POSITIONAL+=("$arg")
  fi
done
set -- "${POSITIONAL[@]+"${POSITIONAL[@]}"}"

USAGE="Usage: generate_systemd_units.sh <project-root> <pack-name> <linux-user> [output-path] [--unit=swarm|operator|front-desk]"
PROJECT_ROOT="${1:?$USAGE}"
PACK_NAME="${2:?$USAGE}"
LINUX_USER="${3:?$USAGE}"
OUTPUT_PATH="${4:-}"

if [[ "$PROJECT_ROOT" != /* ]]; then
  echo "generate_systemd_units.sh: project-root must be an absolute path, got: $PROJECT_ROOT" >&2
  exit 1
fi

ENV_FILE="/etc/swarmforge/${PACK_NAME}.env"

# BL-366: systemd does NOT search PATH for ExecStart (unlike a shell), so an
# ExecStart naming a bare "bb" fails on every start with "Command bb is not
# executable" - systemd-analyze verify catches this outright. Resolve the
# absolute path HERE, at generate time (this script runs directly on the
# target host - see provision_secondary_host.sh), rather than assuming a
# login PATH that a systemd-launched process never has. Required (not
# best-effort): the operator unit's ExecStart runs bb directly, so a unit
# cannot be generated at all if bb cannot be found.
BB_BIN="$(command -v bb || true)"
if [[ -z "$BB_BIN" ]]; then
  echo "generate_systemd_units.sh: cannot resolve an absolute path for 'bb' via PATH on this host - systemd requires an absolute ExecStart and cannot search PATH itself" >&2
  exit 1
fi

# BL-366 DEFECT A': one layer down from ExecStart itself. systemd hands units
# a minimal PATH (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/snap/bin)
# that excludes a user-local bin dir like ~/.local/bin - so even a unit whose
# OWN ExecStart is already absolute (swarm, front-desk) starts, then dies the
# moment the script it launches shells out to `bb`/`node`/`claude` and can't
# find them. Best-effort for node/claude (launched only by the SCRIPTS these
# units invoke, not by this generator's own ExecStart): if resolvable here,
# include their directory; if not, this generator does not block on it - a
# missing interpreter fails later, at the launched script's own boundary.
MINIMAL_SYSTEMD_PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/snap/bin"
EXTRA_PATH_DIRS="$(dirname "$BB_BIN")"
for interpreter in node claude; do
  resolved="$(command -v "$interpreter" || true)"
  if [[ -n "$resolved" ]]; then
    EXTRA_PATH_DIRS="$EXTRA_PATH_DIRS:$(dirname "$resolved")"
  fi
done
UNIT_PATH="$EXTRA_PATH_DIRS:$MINIMAL_SYSTEMD_PATH"

case "$UNIT_TYPE" in
swarm)
  UNIT="$(cat <<EOF
[Unit]
Description=SwarmForge secondary swarm ($PACK_NAME)
After=network-online.target
Wants=network-online.target
StartLimitIntervalSec=0

[Service]
Type=oneshot
RemainAfterExit=yes
User=$LINUX_USER
WorkingDirectory=$PROJECT_ROOT
Environment=SWARMFORGE_TERMINAL=none
Environment=PATH=$UNIT_PATH
EnvironmentFile=-$ENV_FILE
ExecStart=$PROJECT_ROOT/swarm $PROJECT_ROOT --pack $PACK_NAME
ExecStop=$PROJECT_ROOT/swarm-kill
TimeoutStartSec=120
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF
)"
  ;;
operator)
  UNIT="$(cat <<EOF
[Unit]
Description=SwarmForge operator runtime ($PACK_NAME)
After=network-online.target
Wants=network-online.target
StartLimitIntervalSec=0

[Service]
Type=simple
User=$LINUX_USER
WorkingDirectory=$PROJECT_ROOT
Environment=PATH=$UNIT_PATH
EnvironmentFile=-$ENV_FILE
ExecStart=$BB_BIN $PROJECT_ROOT/swarmforge/scripts/operator_runtime.bb $PROJECT_ROOT
ExecStop=/usr/bin/touch $PROJECT_ROOT/.swarmforge/operator/stop
KillMode=control-group
TimeoutStopSec=60
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF
)"
  ;;
front-desk)
  UNIT="$(cat <<EOF
[Unit]
Description=SwarmForge front desk - bridge + Telegram bot ($PACK_NAME)
After=network-online.target
Wants=network-online.target
StartLimitIntervalSec=0

[Service]
Type=forking
User=$LINUX_USER
WorkingDirectory=$PROJECT_ROOT
Environment=PATH=$UNIT_PATH
EnvironmentFile=-$ENV_FILE
PIDFile=$PROJECT_ROOT/.swarmforge/operator/front-desk-supervisor.pid
ExecStart=$PROJECT_ROOT/swarmforge/scripts/launch_front_desk.sh $PROJECT_ROOT
ExecStop=/usr/bin/touch $PROJECT_ROOT/.swarmforge/operator/front-desk-supervisor.stop
KillMode=control-group
TimeoutStopSec=60
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF
)"
  ;;
*)
  echo "generate_systemd_units.sh: unknown --unit=$UNIT_TYPE (expected swarm, operator, or front-desk)" >&2
  exit 1
  ;;
esac

if [[ -n "$OUTPUT_PATH" ]]; then
  printf '%s\n' "$UNIT" > "$OUTPUT_PATH"
else
  printf '%s\n' "$UNIT"
fi
