'use strict';

// BL-308: step handlers for "the morning briefing is still generated when
// the swarm is banked (no coordinator alive)". This feature shares its
// Background and a few Given steps verbatim with BL-258's own feature
// (briefingGenerationScheduleSteps.js, registered earlier in index.js, so
// its handlers own that shared text - see memory
// "Gherkin step registry shared Background"): "a swarm whose daily
// briefing is generated by a scheduled trigger at a configured morning
// time" (Background), "a day with no briefing yet", "today's briefing has
// already been generated", "the configured morning time is reached", and
// "the morning trigger fires again the same day". That shared file's
// runHarness/handlers were extended (this ticket) to thread an optional
// ctx.hibernated flag through to briefing_generation_harness.bb - this
// file only sets ctx.hibernated before those shared When steps fire, and
// owns every step text unique to this feature.
//
// The real end-to-end daemon wiring (a live handoffd.bb process, real
// hibernation.json, real backlog dirs, fake tmux) is covered separately by
// swarmforge/scripts/test/test_handoffd_banked_briefing_wiring.sh.
const path = require('node:path');
const fs = require('node:fs');
const os = require('node:os');
const { execFileSync } = require('node:child_process');

const SWARMFORGE_SCRIPTS = path.join(__dirname, '..', '..', '..', 'swarmforge', 'scripts');
const EMAIL_HARNESS = path.join(SWARMFORGE_SCRIPTS, 'test', 'briefing_email_harness.bb');
const DAY_KEY = '2026-07-10';

function ensureBriefingsDir(ctx) {
  if (!ctx.briefingsDir) {
    ctx.briefingsDir = fs.mkdtempSync(path.join(os.tmpdir(), 'aps-banked-briefing-'));
  }
  return ctx.briefingsDir;
}

function runEmailHarness(briefingsDir, mode) {
  const out = execFileSync('bb', [EMAIL_HARNESS, briefingsDir, mode], { encoding: 'utf8' });
  return JSON.parse(out);
}

const SECTION_HEADINGS = {
  'recent git activity': '## Recent git activity',
  'backlog counts': '## Backlog counts',
  'parked profile': '## Parked profile',
  'daemon health': '## Daemon health',
};

function registerSteps(registry) {
  // ── banked-composer-fires-01 / lightweight-content-02 ────────────────
  registry.define(/^the swarm is hibernated with no coordinator running$/, (ctx) => {
    ensureBriefingsDir(ctx);
    ctx.hibernated = true;
  });

  registry.define(
    /^the daily briefing for that day is generated by the headless composer$/,
    (ctx) => {
      if (ctx.result.fired !== true) {
        throw new Error(`expected the trigger to fire while hibernated, got: ${JSON.stringify(ctx.result)}`);
      }
      if (!ctx.result.composedFile || !ctx.result.composedFile.endsWith(`${DAY_KEY}.md`)) {
        throw new Error(`expected the headless composer to write today's briefing file directly, got: ${JSON.stringify(ctx.result)}`);
      }
      if (!fs.existsSync(ctx.result.composedFile)) {
        throw new Error(`expected ${ctx.result.composedFile} to exist on disk`);
      }
    }
  );

  registry.define(/^no coordinator nudge is sent$/, (ctx) => {
    if (ctx.result.notified.length !== 0) {
      throw new Error(`expected no coordinator nudge while hibernated, got: ${JSON.stringify(ctx.result.notified)}`);
    }
  });

  // ── lightweight-content-02 ────────────────────────────────────────────
  registry.define(/^the generated briefing is labeled as a parked, lightweight briefing$/, (ctx) => {
    const firstLine = (ctx.result.composedContent || '').split('\n')[0];
    if (!/^Swarm parked - lightweight briefing/.test(firstLine)) {
      throw new Error(`expected the briefing's first line to label it parked/lightweight, got: ${JSON.stringify(firstLine)}`);
    }
  });

  registry.define(/^it includes a "([^"]+)" section$/, (ctx, section) => {
    const heading = SECTION_HEADINGS[section];
    if (!heading) {
      throw new Error(`unknown section "${section}" - no known heading mapping`);
    }
    if (!(ctx.result.composedContent || '').includes(heading)) {
      throw new Error(`expected the composed briefing to include a "${heading}" section, got: ${JSON.stringify(ctx.result.composedContent)}`);
    }
  });

  // ── full-forge-unaffected-03 ──────────────────────────────────────────
  registry.define(/^the swarm is running with a live coordinator$/, (ctx) => {
    ensureBriefingsDir(ctx);
    ctx.hibernated = false;
  });

  registry.define(/^the coordinator is nudged to compose the briefing$/, (ctx) => {
    if (ctx.result.notified.length !== 1) {
      throw new Error(`expected exactly one coordinator nudge when not hibernated, got: ${JSON.stringify(ctx.result.notified)}`);
    }
  });

  registry.define(/^the headless composer does not write the briefing itself$/, (ctx) => {
    if (ctx.result.composedFile) {
      throw new Error(`expected the headless composer to never write when not hibernated, got: ${JSON.stringify(ctx.result.composedFile)}`);
    }
  });

  // ── idempotent-no-double-generate-04 ──────────────────────────────────
  // Reuses the same "the swarm is hibernated with no coordinator running"
  // Given registered above (sets ctx.hibernated before BL-258's shared
  // "today's briefing has already been generated" / "the morning trigger
  // fires again the same day" steps run).
  registry.define(/^no second briefing for that day is generated$/, (ctx) => {
    if (ctx.result.fired !== false) {
      throw new Error(`expected no second generation for an already-generated day, got: ${JSON.stringify(ctx.result)}`);
    }
    if (ctx.result.composedFile) {
      throw new Error(`expected the headless composer to never fire a second time, got: ${JSON.stringify(ctx.result.composedFile)}`);
    }
  });

  // ── mid-day-relaunch-no-double-send-05 ────────────────────────────────
  // Exercises the SEND path's own, unmodified dedup (briefing_email_lib.bb's
  // .sent.json bookkeeping, BL-214) - it dedupes strictly by file name, so
  // whichever path (headless composer or coordinator) authored the file,
  // and regardless of the swarm's hibernation state at send time, an
  // already-sent day is never sent twice. Per the ticket: "verify this, do
  // not rebuild it."
  registry.define(
    /^the swarm was hibernated and its banked briefing for today was already generated and sent$/,
    (ctx) => {
      const dir = ensureBriefingsDir(ctx);
      fs.writeFileSync(
        path.join(dir, `${DAY_KEY}.md`),
        'Swarm parked - lightweight briefing for 2026-07-10\n\nBody.\n'
      );
      fs.writeFileSync(path.join(dir, '.sent.json'), JSON.stringify({ sent: [`${DAY_KEY}.md`] }));
    }
  );

  registry.define(/^the swarm relaunches to a live coordinator later the same day$/, (ctx) => {
    ctx.emailResult = runEmailHarness(ensureBriefingsDir(ctx), 'success');
  });

  registry.define(/^no second email is sent for that day's briefing$/, (ctx) => {
    if (ctx.emailResult.emailsSent !== 0 || ctx.emailResult.sent.length !== 0) {
      throw new Error(`expected no second send for an already-sent banked briefing, got: ${JSON.stringify(ctx.emailResult)}`);
    }
  });
}

module.exports = { registerSteps };
