'use strict';

// BL-258: step handlers for the headless-morning-briefing-generation
// feature. Drives the real briefing_generation_schedule_lib.bb through
// briefing_generation_harness.bb - fake :notify!/:log! adapters (no real
// tmux) and an INJECTED now-ms (no real timer/clock), matching the
// ticket's own qa_e2e_procedure ("clock injected; no real timer; no real
// email send"). The real end-to-end daemon wiring (a live handoffd.bb
// process, real conf, fake tmux) is covered separately by
// swarmforge/scripts/test/test_handoffd_briefing_generation_wiring.sh.
const path = require('node:path');
const fs = require('node:fs');
const os = require('node:os');
const { execFileSync } = require('node:child_process');

const SWARMFORGE_SCRIPTS = path.join(__dirname, '..', '..', '..', 'swarmforge', 'scripts');
const LIB = path.join(SWARMFORGE_SCRIPTS, 'briefing_generation_schedule_lib.bb');
const HARNESS = path.join(SWARMFORGE_SCRIPTS, 'test', 'briefing_generation_harness.bb');
const DAY_KEY = '2026-07-10';

function mkFixtureRoot() {
  return fs.mkdtempSync(path.join(os.tmpdir(), 'aps-briefing-generation-'));
}

function ensureBriefingsDir(ctx) {
  if (!ctx.briefingsDir) {
    ctx.briefingsDir = mkFixtureRoot();
  }
  return ctx.briefingsDir;
}

function runHarness(briefingsDir, nowIso, hour, minute) {
  const out = execFileSync('bb', [HARNESS, briefingsDir, nowIso, String(hour), String(minute)], { encoding: 'utf8' });
  return JSON.parse(out);
}

function writeBriefing(briefingsDir, dayKey) {
  fs.writeFileSync(path.join(briefingsDir, `${dayKey}.md`), 'Headline: shipped a thing\n\nBody.\n');
}

function morningTimeIso(dayKey, hour, minute) {
  return `${dayKey}T${String(hour).padStart(2, '0')}:${String(minute).padStart(2, '0')}:00Z`;
}

function registerSteps(registry) {
  // ── Background ───────────────────────────────────────────────────────
  registry.define(
    /^a swarm whose daily briefing is generated by a scheduled trigger at a configured morning time$/,
    (ctx) => {
      ensureBriefingsDir(ctx);
      ctx.hour = 7;
      ctx.minute = 0;
    }
  );

  // ── morning-trigger-01 ──────────────────────────────────────────────
  registry.define(/^a day with no briefing yet$/, (ctx) => {
    if (fs.existsSync(path.join(ensureBriefingsDir(ctx), `${DAY_KEY}.md`))) {
      throw new Error('fixture setup error: expected no briefing file yet');
    }
  });

  registry.define(/^the configured morning time is reached$/, (ctx) => {
    ctx.result = runHarness(ensureBriefingsDir(ctx), morningTimeIso(DAY_KEY, ctx.hour, ctx.minute), ctx.hour, ctx.minute);
  });

  registry.define(/^the daily briefing for that day is generated$/, (ctx) => {
    if (ctx.result.fired !== true) {
      throw new Error(`expected the trigger to fire at the configured morning time, got: ${JSON.stringify(ctx.result)}`);
    }
    if (!ctx.result.notified.some((text) => text.includes(`docs/briefings/${DAY_KEY}.md`))) {
      throw new Error(`expected the nudge to name today's target file, got: ${JSON.stringify(ctx.result.notified)}`);
    }
  });

  // ── headless-independent-02 ─────────────────────────────────────────
  registry.define(/^the swarm is running headless with no VS Code host$/, () => {
    // Non-behavioral: the trigger (briefing_generation_schedule_lib.bb,
    // driven here through pure Babashka + the harness's fake adapters) has
    // zero VS Code host dependency - asserted statically, not fixtured.
    const libSrc = fs.readFileSync(LIB, 'utf8');
    if (/vscode/i.test(libSrc)) {
      throw new Error('expected briefing_generation_schedule_lib.bb to have zero VS Code host dependency');
    }
  });

  registry.define(/^the briefing is still generated by the headless schedule$/, (ctx) => {
    ctx.result = runHarness(ensureBriefingsDir(ctx), morningTimeIso(DAY_KEY, ctx.hour, ctx.minute), ctx.hour, ctx.minute);
    if (ctx.result.fired !== true) {
      throw new Error(`expected the headless schedule alone (no VS Code host process involved) to still fire, got: ${JSON.stringify(ctx.result)}`);
    }
  });

  // ── idempotent-once-per-day-03 ──────────────────────────────────────
  registry.define(/^today's briefing has already been generated$/, (ctx) => {
    writeBriefing(ensureBriefingsDir(ctx), DAY_KEY);
  });

  registry.define(/^the morning trigger fires again the same day$/, (ctx) => {
    // Well past the configured morning time, same UTC day.
    ctx.result = runHarness(ensureBriefingsDir(ctx), `${DAY_KEY}T20:00:00Z`, ctx.hour, ctx.minute);
  });

  registry.define(/^no second briefing for that day is generated or emailed$/, (ctx) => {
    if (ctx.result.fired !== false || ctx.result.notified.length !== 0) {
      throw new Error(`expected no second generation nudge for an already-generated day, got: ${JSON.stringify(ctx.result)}`);
    }
    // "or emailed": BL-214's own send path (briefing_email_lib.bb) is a
    // wholly separate function this trigger never calls - a skipped
    // generation nudge structurally cannot cause a second email.
  });

  // ── configurable-time-04 ────────────────────────────────────────────
  registry.define(/^the morning-time setting is "([^"]+)"$/, (ctx, timeStr) => {
    const [hour, minute] = timeStr.split(':').map(Number);
    ctx.hour = hour;
    ctx.minute = minute;
    ctx.timeStr = timeStr;
  });

  registry.define(/^that time is reached$/, (ctx) => {
    const nowIso = morningTimeIso(DAY_KEY, ctx.hour, ctx.minute);
    ctx.result = runHarness(ensureBriefingsDir(ctx), nowIso, ctx.hour, ctx.minute);

    // Proves the CONFIGURED time actually drives the decision, not a
    // hardcoded one: one minute before that SAME configured time, on a
    // fresh (still-empty) fixture dir, the trigger must not yet be due.
    const beforeIso = new Date(new Date(nowIso).getTime() - 60000).toISOString().replace(/\.\d{3}Z$/, 'Z');
    ctx.beforeResult = runHarness(mkFixtureRoot(), beforeIso, ctx.hour, ctx.minute);
  });

  registry.define(/^the briefing is generated then, not at a hardcoded time$/, (ctx) => {
    if (ctx.result.fired !== true) {
      throw new Error(`expected the trigger to fire exactly at the configured time "${ctx.timeStr}", got: ${JSON.stringify(ctx.result)}`);
    }
    if (ctx.beforeResult.fired !== false) {
      throw new Error(
        `expected the trigger NOT to fire one minute before the configured time "${ctx.timeStr}" (proves the time is read from config, not hardcoded), got: ${JSON.stringify(ctx.beforeResult)}`
      );
    }
  });
}

module.exports = { registerSteps };
