'use strict';

// Combines every domain's step handlers into the project step registry.
// The ticket's step-handler surface allowlist is tmux socket discovery,
// .swarmforge state parsing, handoff protocol, backlog parsing, and grid
// layout logic (local-engineering.prompt); domains are added here
// incrementally as tickets need their vocabulary, same as backlogSteps.
const DOMAINS = [
  require('./backlogSteps'),
  require('./daemonWorkflowSteps'),
  require('./launchSpawnFailureSteps'),
  require('./mailboxIntakeSteps'),
  require('./strykerSandboxSiblingsSteps'),
  require('./dispatchGapSteps'),
  require('./backlogDepthSteps'),
  require('./remoteWakeupSteps'),
  require('./rateLimitCooldownSteps'),
  require('./emailMissingKeySteps'),
  require('./briefingEmailSteps'),
  require('./briefingDiagramSteps'),
  require('./recertAddressSteps'),
  require('./webhookSecretFixtureSteps'),
  require('./providerErrorTaxonomySteps'),
  require('./gherkinMutationSteps'),
  require('./swarmMutationCostPrepassSteps'),
  require('./providerObservabilityParitySteps'),
  require('./pwaLabelCatalogSteps'),
  require('./readyForNextPromotionSteps'),
  require('./swarmIntakeEnvRouteSteps'),
  require('./pwaFontSizeSteps'),
  require('./complianceBatterySteps'),
  require('./burndownEtaSteps'),
  require('./pwaTranslatedContentSteps'),
  require('./sidecarNoOrphanSteps'),
  require('./recruiterDiscoverSteps'),
  require('./backlogFoldersStatusSteps'),
  require('./backendSwitchSteps'),
  require('./docsWindowsClaimSteps'),
  require('./effortDialSteps'),
  require('./accessibilitySteps'),
  require('./gateAnswerSteps'),
  require('./deviceRegistrySteps'),
  require('./coordinatorProvisioningSteps'),
  require('./telegramAdapterSteps'),
  require('./recertSenderAllowlistSteps'),
  require('./pwaCacheStampSteps'),
  require('./qaIntegratesCoordinatorBookkeepsSteps'),
  require('./recruiterAcquireSteps'),
  require('./recruiterQualifySteps'),
  require('./recruiterRankRecommendSteps'),
  require('./compositeNodeSteps'),
  require('./bakeoffRosterSteps'),
  require('./bakeoffPipelineSteps'),
  require('./coordinatorLossSteps'),
  require('./fleetConsoleSteps'),
  require('./docsSearchFilterSteps'),
  require('./docsImplementedStatusSteps'),
  require('./suiteDurationReadoutSteps'),
  require('./coChangeSteps'),
  require('./needsApprovalSteps'),
  require('./dependencyGateSteps'),
  require('./docsUntranslatedFlagSteps'),
  require('./briefingGenerationScheduleSteps'),
  require('./bankedBriefingHeadlessSteps'),
  require('./closingContextClearSteps'),
  require('./approvalTicketDetailSteps'),
  require('./briefingEnrichmentSteps'),
  require('./pwaEnrichmentSteps'),
  require('./onboardingContractSteps'),
  require('./notDoneCountSteps'),
  require('./coChangeCwdSteps'),
  require('./resourceSamplerActivationSteps'),
  require('./gatesListSteps'),
  require('./onboardingPromptsSteps'),
  require('./stageDwellFixedClockSteps'),
  require('./recertListenSteps'),
  require('./costHealthSidecarHeadlessSteps'),
  require('./burnRateSteps'),
  require('./supportThreadEmailEchoSteps'),
  require('./recertBacklogContextSteps'),
  require('./telegramTopicThreadsSteps'),
  require('./operatorThreadLifecycleSteps'),
  require('./operatorLongtermMemorySteps'),
  require('./briefingDiagramCidAttachmentsSteps'),
  require('./operatorProactiveNotifySteps'),
  require('./recertInboundServerlessHandlerSteps'),
  require('./burndownLineChartSteps'),
  require('./recertInboundWebhookSteps'),
  require('./operatorDecideStatusSteps'),
  require('./suiteDurationPwaSidecarSteps'),
  require('./operatorCoordinatorHandoffSteps'),
  require('./frontDeskHeadlessLauncherSteps'),
  require('./pwaCollapsibleSectionsSteps'),
  // BL-300: registered BEFORE swarmEventStreamSteps - its own "a backlog
  // item that has newly (started being worked|completed)" pattern is more
  // specific than (and would otherwise be shadowed by) BL-296's own
  // greedy catch-all "a backlog item (.+)" below. Both patterns can match
  // the same PREFIX text, so registration order decides which handler a
  // given full string resolves to - registry.resolve is first-match, not
  // most-specific-match (see stepRegistry.js).
  require('./conciergeRuntimeWiringSteps'),
  require('./swarmEventStreamSteps'),
  require('./frontDeskAutoOpenSubjectSteps'),
  require('./gherkinDetailListenSteps'),
  require('./conciergeTopicRoutingSteps'),
  require('./conciergeTopicReplySteps'),
  require('./conciergeTopicCompletionSteps'),
  require('./conciergeNeedsApprovalSteps'),
  require('./frontDeskPollResilienceSteps'),
  require('./frontDeskSupervisorRecoverySteps'),
  require('./operatorSystemdSupervisionSteps'),
  require('./operatorCooldownResilienceSteps'),
  require('./operatorAskAwaitSteps'),
  require('./operatorAutoHibernateSteps'),
  require('./operatorSeedRaceLaunchGraceSteps'),
  require('./burnMeterMasterResidentSteps'),
  require('./backlogDepthCapOverrideSteps'),
  require('./coordinatorModelConfigurableSteps'),
  require('./coordinatorInfraTestConfigLeakSteps'),
  require('./contextClearAllRolesSteps'),
  require('./replyRelayAtLeastOnceSteps'),
];

function registerSteps(registry) {
  for (const domain of DOMAINS) {
    domain.registerSteps(registry);
  }
}

module.exports = { registerSteps };
