# mutation-stamp: sha256=77d8d31d312dc4c5d8d017bd5390132c6b1b60aab6a610aa7b2161b7e9920c6e
# acceptance-mutation-manifest-begin
# {"version":1,"tested_at":"2026-07-10T19:51:29.552048334Z","feature_name":"the daily briefing is generated every morning even when the swarm runs headless","feature_path":"/home/carillon/swarmforgevc/.worktrees/hardender/specs/features/BL-258-headless-morning-briefing-schedule.feature","background_hash":"337aa3835d62d1add0d205b01e542f495b10632e1e78c292ce9de14c2c4e7b4e","implementation_hash":"unknown","scenarios":[{"index":3,"name":"the morning time is read from configuration","scenario_hash":"ecf8917aee4122578ae7d30d6e683ecf09ca14d504341edcd6f053b63d391cb1","mutation_count":2,"result":{"Total":2,"Killed":2,"Survived":0,"Errors":0},"tested_at":"2026-07-10T19:51:29.552048334Z"}]}
# acceptance-mutation-manifest-end

Feature: the daily briefing is generated every morning even when the swarm runs headless

  # Operator direction 2026-07-10 ("I need this scheduled every morning, to start
  # with"). Today the briefing's WRITE trigger is the VS Code host's once-per-day
  # timer (BL-099); the daemon only handles the SEND of an already-committed
  # docs/briefings/<date>.md (BL-214). So a HEADLESS operator (no VS Code host) may
  # never get the briefing generated. This adds a headless, host-independent MORNING
  # trigger so the briefing is written (and thus emailed by BL-214) each morning.
  #
  # REUSE: keep BL-099's briefing content and BL-214's daemon send path. This adds
  # only the scheduled GENERATION trigger. The morning time is CONFIGURABLE
  # (swarmforge.conf), not hardcoded. Idempotent: at most one briefing per day —
  # never double-generate or double-email if both the host timer and the daemon
  # schedule are present. No self-scheduling by role agents; the trigger is
  # daemon/host infrastructure, consistent with BL-099 ("roles must not
  # self-schedule").

  Background:
    Given a swarm whose daily briefing is generated by a scheduled trigger at a configured morning time

  # BL-258 morning-trigger-01
  Scenario: the briefing is generated at the configured morning time
    Given a day with no briefing yet
    When the configured morning time is reached
    Then the daily briefing for that day is generated

  # BL-258 headless-independent-02
  Scenario: the briefing is generated with no VS Code host running
    Given the swarm is running headless with no VS Code host
    When the configured morning time is reached
    Then the briefing is still generated by the headless schedule

  # BL-258 idempotent-once-per-day-03
  Scenario: at most one briefing is generated per day
    Given today's briefing has already been generated
    When the morning trigger fires again the same day
    Then no second briefing for that day is generated or emailed

  # BL-258 configurable-time-04
  Scenario Outline: the morning time is read from configuration
    Given the morning-time setting is "<time>"
    When that time is reached
    Then the briefing is generated then, not at a hardcoded time

    Examples:
      | time  |
      | 07:00 |
      | 09:30 |
