Feature: The morning briefing is still generated when the swarm is banked (no coordinator alive)

  # Generation is coordinator-agentic (BL-258): the morning trigger only nudges
  # the coordinator to compose docs/briefings/<day>.md. In concierge-banked mode
  # (BL-307 auto-hibernate) there is no coordinator, so the nudge lands on
  # nobody and no briefing file is ever composed - the healthy BL-214 send
  # sweep then has nothing to send and the morning email silently stops. This
  # adds a headless, no-agent composer that fires only while banked, reusing
  # the existing hibernation-state signal, day-key idempotency gate, and
  # plain-markdown briefing format the send path already reads.

  Background:
    Given a swarm whose daily briefing is generated by a scheduled trigger at a configured morning time

  # BL-308 banked-composer-fires-01
  Scenario: the swarm is banked, so the headless composer writes the briefing instead of nudging a coordinator
    Given the swarm is hibernated with no coordinator running
    And a day with no briefing yet
    When the configured morning time is reached
    Then the daily briefing for that day is generated by the headless composer
    And no coordinator nudge is sent

  # BL-308 lightweight-content-02
  Scenario Outline: the banked briefing is labeled lightweight and includes cheap headless signals
    Given the swarm is hibernated with no coordinator running
    And a day with no briefing yet
    When the configured morning time is reached
    Then the generated briefing is labeled as a parked, lightweight briefing
    And it includes a "<section>" section

    Examples:
      | section                        |
      | recent git activity            |
      | backlog counts                 |
      | parked profile                 |
      | daemon health                  |

  # BL-308 full-forge-unaffected-03
  Scenario: the swarm is not banked, so the existing coordinator-nudge behavior is unchanged
    Given the swarm is running with a live coordinator
    And a day with no briefing yet
    When the configured morning time is reached
    Then the coordinator is nudged to compose the briefing
    And the headless composer does not write the briefing itself

  # BL-308 idempotent-no-double-generate-04
  Scenario: a briefing already generated today is never regenerated by the banked composer
    Given the swarm is hibernated with no coordinator running
    And today's briefing has already been generated
    When the morning trigger fires again the same day
    Then no second briefing for that day is generated

  # BL-308 mid-day-relaunch-no-double-send-05
  Scenario: a mid-day relaunch after a banked briefing was already sent does not trigger a second send
    Given the swarm was hibernated and its banked briefing for today was already generated and sent
    When the swarm relaunches to a live coordinator later the same day
    Then no second email is sent for that day's briefing
