#!/usr/bin/env bb
;; BL-571 (coder.prompt Invariants, BL-654): property tests over
;; mono_router_lib.bb's single-resident predicates, encoding the ticket's
;; declared invariant:
;;
;;   "Under every rotation value that means single-resident, ensure never
;;    respawns a role the launcher deliberately left dormant."
;;
;; The invariant's executable core is PREDICATE PARITY: the launcher
;; (is_sequential_dormant) accepts exactly {router, sequential} as
;; single-resident, so for every conf/identity shape the launcher would
;; treat as single-resident - generated BY CONSTRUCTION across both values,
;; with and without the `config ` prefix, embedded in arbitrary surrounding
;; conf lines - single-resident-rotation? / ...-from-identity? must be true;
;; and for every near-miss value (derived from a real value by mutation:
;; suffixed, truncated, case-shifted, replaced) both must be false. The
;; "ensure never respawns" tail quantifies over the live ensure process
;; (real tmux respawn calls) which a generator cannot drive - that half is
;; asserted end-to-end for BOTH values by test_swarm_ensure.sh's
;; empty-respawn-log fixtures (the BL-530 router case and this ticket's
;; sequential twin), not silently unencoded.
;;
;; Also pinned per the ticket's ROTATE_HOME fence: the router-only
;; predicates never widen - for every generated sequential shape they stay
;; false.
;;
;; Non-vacuity proven by hand at authoring time: narrowing
;; single-resident-rotation?'s regex back to router-only fails the
;; sequential rows on the first draw; widening it to any rotation value
;; fails the near-miss rows immediately. Both restored.

(ns bl571-single-resident-rotation-property-runner
  (:require [babashka.fs :as fs]
            [clojure.string :as str]))

(load-file (str (fs/path (fs/parent (fs/canonicalize *file*)) ".." "mono_router_lib.bb")))

(def runs (or (some-> (System/getenv "PROPERTY_RUNS") parse-long) 500))
(def failures (atom []))
(def ^:private rng (java.util.Random. 571))
(defn- rint [n] (.nextInt rng (int n)))
(defn- rpick [coll] (nth (vec coll) (rint (count coll))))
(defn- rbool [] (.nextBoolean rng))

(def single-resident-values ["router" "sequential"])

;; near-misses derived from the real values BY CONSTRUCTION - the exact
;; transformations a sloppy regex conflates
(defn- near-miss []
  (let [base (rpick single-resident-values)]
    (rpick [(str base "ly")              ; sequentially / routerly
            (subs base 0 (dec (count base)))
            (str/upper-case base)
            (str base "2")
            "classic"
            "parallel"])))

(def noise-lines
  ["config active_backlog_max_depth 3"
   "window coder aider"
   "# rotation router (commented mention, not a directive)"
   ""
   "config flow_watchdog_warn_ms 900000"])

(defn- conf-with [rotation-line]
  (let [before (repeatedly (rint 3) #(rpick noise-lines))
        after (repeatedly (rint 3) #(rpick noise-lines))]
    (str/join "\n" (concat before [rotation-line] after))))

(def positive-reached (atom 0))
(def sequential-reached (atom 0))
(def negative-reached (atom 0))

(dotimes [_ runs]
  (if (rbool)
    ;; positive shape: a value the launcher accepts, either conf form
    (let [value (rpick single-resident-values)
          line (str (if (rbool) "config rotation " "rotation ") value)
          conf (conf-with line)
          identity-text (str "rotation\t" value "\n")]
      (swap! positive-reached inc)
      (when (= value "sequential") (swap! sequential-reached inc))
      (when-not (mono-router-lib/single-resident-rotation? conf)
        (swap! failures conj (str "FAIL: launcher-accepted conf not recognised: " (pr-str conf))))
      (when-not (mono-router-lib/single-resident-rotation-from-identity? identity-text)
        (swap! failures conj (str "FAIL: launcher-accepted identity not recognised: " (pr-str identity-text))))
      ;; ROTATE_HOME fence: the router-only pair never widens
      (when (and (= value "sequential")
                 (or (mono-router-lib/conf-rotation-router? conf)
                     (mono-router-lib/rotation-router-from-identity? identity-text)))
        (swap! failures conj (str "FAIL fence: router-only predicate widened to sequential: " (pr-str conf)))))
    ;; negative shape: a constructed near-miss, or no rotation line at all
    (let [miss? (rbool)
          conf (if miss?
                 (conf-with (str (if (rbool) "config rotation " "rotation ") (near-miss)))
                 (str/join "\n" (repeatedly (inc (rint 4)) #(rpick noise-lines))))
          identity-text (if miss? (str "rotation\t" (near-miss) "\n") "pack\tclassic\n")]
      (swap! negative-reached inc)
      (when (mono-router-lib/single-resident-rotation? conf)
        (swap! failures conj (str "FAIL: non-single-resident conf recognised: " (pr-str conf))))
      (when (mono-router-lib/single-resident-rotation-from-identity? identity-text)
        (swap! failures conj (str "FAIL: non-single-resident identity recognised: " (pr-str identity-text)))))))

;; asserted reachability floors, never hoped-for
(when (< @positive-reached 100)
  (swap! failures conj (str "FAIL reachability: only " @positive-reached " positive shapes")))
(when (< @sequential-reached 40)
  (swap! failures conj (str "FAIL reachability: only " @sequential-reached " sequential shapes")))
(when (< @negative-reached 100)
  (swap! failures conj (str "FAIL reachability: only " @negative-reached " negative shapes")))

(if (seq @failures)
  (do (doseq [f @failures] (binding [*out* *err*] (println f)))
      (println (str "\n" (count @failures) " failure(s)"))
      (System/exit 1))
  (println (str "bl571_single_resident_rotation_property_runner: ok (" runs " runs, "
                @positive-reached " positive, " @sequential-reached " sequential, "
                @negative-reached " negative)")))
