#!/usr/bin/env bb
;; PROPERTY test over master_main_reconcile_lib.bb, covering both BL-891's
;; original 2 declared invariants and BL-919's own 3 declared invariants
;; (coder-authored first, per BL-654). BL-919's invariants:
;;
;;   1. "The sweep never stashes, resets, rebases, or force-updates, and
;;      every commit reachable before it runs is still reachable after."
;;   2. "A sweep that does not complete a merge leaves the checkout exactly
;;      as it found it - uncommitted changes untouched, never left
;;      mid-merge."
;;   3. "Narrowing the gate is strictly one-directional: every working-tree
;;      state the old gate allowed to reconcile still reconciles. The fix
;;      may only widen what proceeds, never block something that used to
;;      pass."
;;
;; Invariants 1 and 2 restate BL-891's own invariants 1 and 2 almost word
;; for word - unsurprising, since master-main-reconcile-merge! (the ONE
;; state-mutating adapter) is UNCHANGED by BL-919: still a plain
;; `git merge --no-edit origin/main`, abort-on-any-failure. Split across two
;; layers, same posture this file has always documented: this file proves
;; the PURE decision/gating logic (no real git process, no real clock)
;; against a randomized generator; the real-git half of each invariant -
;; local-only commits genuinely reachable after a real `git merge`, the
;; working tree genuinely byte-identical after a real conflict abort or a
;; real non-overlapping-dirt reconcile - is proven concretely against a
;; real git fixture by test_handoffd_master_main_reconcile_wiring.sh.
;; sweep!'s only state-mutating adapter is `:merge!`; invariants 1 and 2
;; reduce, at this layer, to the same single load-bearing claim each
;; generated scenario checks: `:merge!` fires if-and-only-if this tick is
;; genuinely safe to mutate (behind>0 AND no dirty/merge-changed path
;; overlap) - so a risky tree is NEVER touched, and reconciliation is
;; ATTEMPTED whenever it is safe (never silently stuck); and `:surface!`
;; fires if-and-only-if this tick ends BLOCKED, so a block is always loud,
;; never silent.
;;
;; Invariant 3 is BL-919's genuinely NEW property: it compares this
;; implementation's decision against an independent restatement of the OLD
;; (BL-891-era) blanket "any dirt blocks" gate, over the SAME generated
;; scenario, and asserts the old gate's :should-reconcile is never lost.

(ns master-main-reconcile-lib-property-runner
  (:require [babashka.fs :as fs]
            [clojure.set :as set]))

(load-file (str (fs/path (fs/parent (fs/canonicalize *file*)) ".." "master_main_reconcile_lib.bb")))

(def runs (or (some-> (System/getenv "PROPERTY_RUNS") parse-long) 500))
(def failures (atom []))

(def created-temp-dirs (atom []))
(.addShutdownHook (Runtime/getRuntime)
                   (Thread. (fn [] (doseq [d @created-temp-dirs] (try (fs/delete-tree d) (catch Exception _ nil))))))

(defn mk-tmp []
  (let [d (str (fs/create-temp-dir {:prefix "master-main-reconcile-prop-"}))]
    (swap! created-temp-dirs conj d)
    d))

;; ── seeded generator (identical LCG shape to push_sweep_lib_property_
;;    runner.bb / ambulance_lib_property_runner.bb) ─────────────────────────

(defn- step [s] (mod (+ (* s 1103515245) 12345) 2147483648))
(defn- gen-int [s n] [(mod (quot s 65536) n) (step s)])
(defn- gen-bool [s] (let [[v s'] (gen-int s 2)] [(= 1 v) s']))
(defn- gen-pick [s coll] (let [[i s'] (gen-int s (count coll))] [(nth (vec coll) i) s']))

(defn- report! [prop seed input msg]
  (swap! failures conj (str "FAIL " prop "\n  seed:  " seed "\n  input: " (pr-str input) "\n  " msg)))

(defn- check-all [prop gen-fn pred-fn]
  (loop [i 0 s 11]
    (when (< i runs)
      (let [[input s'] (gen-fn s)
            result (pred-fn input)]
        (when-not (true? result)
          (report! prop s input (str result)))
        (recur (inc i) s')))))

;; BL-654 generator-reach: `behind` is drawn from a small pool WEIGHTED so
;; zero and non-zero are equally common (a wide/uniform int draw would make
;; behind=0 vanishingly rare relative to the interesting nonzero cases, or
;; vice versa) - both branches of reconcile-decision's own zero-check need
;; to be reachable often, not hoped for.
(def behind-pool [0 1 5 22])

;; BL-919 generator-reach: dirty-paths/merge-changed-paths are subsets of a
;; small 3-path pool, generated by an independent include/exclude coin flip
;; PER PATH - this reaches all 2^3 = 8 subsets of each with roughly uniform
;; probability (rather than e.g. picking a single random path per set, which
;; would make "two dirty paths, one overlapping" astronomically rarer than
;; it needs to be for a set-overlap property). With two independent 8-subset
;; draws that is 64 (dirty, merge-changed) combinations per behind/merge-
;; success value - both "some overlap" and "disjoint but both non-empty" are
;; common outcomes, not edge cases the generator only stumbles into.
(def path-pool ["a.txt" "b.txt" "c.txt"])

(defn- gen-subset [s pool]
  (loop [i 0 s s acc #{}]
    (if (= i (count pool))
      [acc s]
      (let [[include? s'] (gen-bool s)]
        (recur (inc i) s' (if include? (conj acc (nth pool i)) acc))))))

(defn gen-scenario [s]
  (let [[behind s1] (gen-pick s behind-pool)
        [dirty-paths s2] (gen-subset s1 path-pool)
        [merge-changed-paths s3] (gen-subset s2 path-pool)
        [merge-success? s4] (gen-bool s3)]
    [{:behind behind :dirty-paths dirty-paths :merge-changed-paths merge-changed-paths
      :merge-success? merge-success?}
     s4]))

;; ── independent oracles: fresh restatements of the gating rules, built
;;    without calling reconcile-decision/sweep! themselves - same posture as
;;    push_sweep_lib_property_runner.bb's own oracle-lacks-qa-approval?. ────
(defn- oracle-overlap? [{:keys [dirty-paths merge-changed-paths]}]
  (boolean (seq (set/intersection (set dirty-paths) (set merge-changed-paths)))))

(defn- oracle-should-mutate? [{:keys [behind] :as scenario}]
  (and (pos? behind) (not (oracle-overlap? scenario))))

(defn- oracle-should-surface? [{:keys [behind merge-success?] :as scenario}]
  (or (and (pos? behind) (oracle-overlap? scenario))
      (and (pos? behind) (not (oracle-overlap? scenario)) (not merge-success?))))

;; BL-919 invariant 3's own independent oracle: the OLD (BL-891-era)
;; blanket gate, restated fresh here rather than by calling any current
;; production code - "any dirt at all blocks, regardless of what it is."
(defn- oracle-old-gate-should-mutate? [{:keys [behind dirty-paths]}]
  (and (pos? behind) (empty? dirty-paths)))

(defn- run-sweep-with-scenario [{:keys [behind dirty-paths merge-changed-paths merge-success?]}]
  (let [dirty-paths-calls (atom 0)
        merge-changed-paths-calls (atom 0)
        merge-calls (atom 0)
        surface-calls (atom 0)
        adapters {:rev-counts! (fn [] {:ahead 0 :behind behind})
                  :dirty-paths! (fn [] (swap! dirty-paths-calls inc) dirty-paths)
                  :merge-changed-paths! (fn [] (swap! merge-changed-paths-calls inc) merge-changed-paths)
                  :merge! (fn [] (swap! merge-calls inc)
                             (if merge-success? {:success true} {:success false :error "conflict"}))
                  :surface! (fn [_msg] (swap! surface-calls inc))
                  :log! (fn [& _parts] nil)}]
    (master-main-reconcile-lib/sweep! (mk-tmp) adapters)
    {:merge-calls @merge-calls :surface-calls @surface-calls}))

;; ── invariant 1: never mutates a tree it is unsafe to touch, always
;;    attempts when safe ────────────────────────────────────────────────
(check-all "master_main_reconcile_lib invariant 1: merge! fires iff (behind>0 AND no dirty/merge-changed overlap) - never touches an unsafe tree"
  gen-scenario
  (fn [scenario]
    (let [{:keys [merge-calls]} (run-sweep-with-scenario scenario)
          expect-mutate? (oracle-should-mutate? scenario)]
      (cond
        (and expect-mutate? (not= 1 merge-calls))
        (str "LIVENESS VIOLATION: oracle says reconcile should be attempted but merge! fired " merge-calls " time(s)")

        (and (not expect-mutate?) (pos? merge-calls))
        (str "SAFETY VIOLATION: oracle says this tick must NOT mutate (unsafe overlap, or already up-to-date) but merge! fired " merge-calls " time(s)")

        :else true))))

;; ── invariant 2: a block is always loud (surfaced), a clean tick never
;;    spuriously alarms ──────────────────────────────────────────────────
(check-all "master_main_reconcile_lib invariant 2: surface! fires iff this tick ends blocked - never silent, never spurious"
  gen-scenario
  (fn [scenario]
    (let [{:keys [surface-calls]} (run-sweep-with-scenario scenario)
          expect-surface? (oracle-should-surface? scenario)]
      (cond
        (and expect-surface? (not= 1 surface-calls))
        (str "LOUDNESS VIOLATION: oracle says this tick is blocked but surface! fired " surface-calls " time(s), not exactly once")

        (and (not expect-surface?) (pos? surface-calls))
        (str "SPURIOUS-ALARM VIOLATION: oracle says this tick is not blocked but surface! fired " surface-calls " time(s)")

        :else true))))

;; ── invariant 3 (BL-919's own): narrowing the gate is strictly
;;    one-directional - every scenario the OLD blanket-dirty gate would
;;    have reconciled, THIS implementation also reconciles. ───────────────
(check-all "master_main_reconcile_lib invariant 3 (BL-919): the old gate's should-reconcile is never lost - narrowing only ever WIDENS what proceeds"
  gen-scenario
  (fn [scenario]
    (let [{:keys [merge-calls]} (run-sweep-with-scenario scenario)
          old-would-reconcile? (oracle-old-gate-should-mutate? scenario)]
      (if (and old-would-reconcile? (not= 1 merge-calls))
        (str "REGRESSION: the pre-BL-919 gate would have reconciled this exact state (behind>0, fully clean tree) but merge! fired " merge-calls " time(s) instead of 1")
        true))))

;; ── non-vacuity: each property MUST actually fail against a deliberately
;;    broken implementation, proven here rather than asserted (BL-654's own
;;    generator-reach rule - a property that can never fail is worth
;;    nothing). ───────────────────────────────────────────────────────────

;; Mutant A: a sweep! that ignores dirty/merge-changed overlap entirely and
;; reconciles whenever behind>0 - exactly the bug invariant 1 exists to
;; prevent (touching a checkout with a real, overlapping local change).
(defn- mutant-ignores-overlap! [dir adapters]
  (let [{:keys [behind]} ((:rev-counts! adapters))]
    (when (pos? behind)
      ((:merge! adapters)))))

(defn- non-vacuity-check-ignores-overlap []
  (let [overlap-scenario {:behind 22 :dirty-paths #{"seed.txt"} :merge-changed-paths #{"seed.txt"} :merge-success? true}
        merge-calls (atom 0)
        adapters {:rev-counts! (fn [] {:ahead 0 :behind 22})
                  :dirty-paths! (fn [] #{"seed.txt"})
                  :merge-changed-paths! (fn [] #{"seed.txt"})
                  :merge! (fn [] (swap! merge-calls inc) {:success true})
                  :surface! (fn [_msg] nil)
                  :log! (fn [& _parts] nil)}]
    (mutant-ignores-overlap! (mk-tmp) adapters)
    (if (and (not (oracle-should-mutate? overlap-scenario)) (pos? @merge-calls))
      (println "non-vacuity confirmed: invariant 1's oracle would flag a mutant that merges an overlapping-dirty tree (merge! fired when it must not)")
      (do (println (str "NON-VACUITY FAILURE (ignores-overlap mutant): expected the oracle to forbid mutation and the mutant to violate it; merge-calls=" @merge-calls))
          (System/exit 1)))))

(non-vacuity-check-ignores-overlap)

;; Mutant B: a sweep! that blocks silently - decides not to reconcile an
;; overlapping-dirty tree (correctly) but never tells the coordinator why.
;; Exactly the bug invariant 2 exists to prevent: staleness that is
;; confidently wrong rather than obviously broken (the ticket's own
;; incident, BL-891's `notes:`).
(defn- mutant-silent-block! [dir adapters]
  (let [{:keys [behind]} ((:rev-counts! adapters))
        dirty-paths ((:dirty-paths! adapters))
        merge-changed-paths ((:merge-changed-paths! adapters))
        overlap? (boolean (seq (set/intersection (set dirty-paths) (set merge-changed-paths))))]
    (when (and (pos? behind) (not overlap?))
      ((:merge! adapters))))
  ;; note: no :surface! call on the dirty-blocked path at all
  nil)

(defn- non-vacuity-check-silent-block []
  (let [overlap-scenario {:behind 22 :dirty-paths #{"seed.txt"} :merge-changed-paths #{"seed.txt"} :merge-success? true}
        surface-calls (atom 0)
        adapters {:rev-counts! (fn [] {:ahead 0 :behind 22})
                  :dirty-paths! (fn [] #{"seed.txt"})
                  :merge-changed-paths! (fn [] #{"seed.txt"})
                  :merge! (fn [] {:success true})
                  :surface! (fn [_msg] (swap! surface-calls inc))
                  :log! (fn [& _parts] nil)}]
    (mutant-silent-block! (mk-tmp) adapters)
    (if (and (oracle-should-surface? overlap-scenario) (zero? @surface-calls))
      (println "non-vacuity confirmed: invariant 2's oracle would flag a mutant that blocks an overlapping-dirty tree without ever surfacing why")
      (do (println (str "NON-VACUITY FAILURE (silent-block mutant): expected the oracle to require surfacing and the mutant to violate it; surface-calls=" @surface-calls))
          (System/exit 1)))))

(non-vacuity-check-silent-block)

;; Mutant C: a "narrower than necessary" regression mutant for invariant 3 -
;; reconciles only when behind is a multiple of 2, an arbitrary extra
;; restriction with nothing to do with dirt/overlap at all. Applied to a
;; scenario the OLD gate would already have reconciled (behind=5, fully
;; clean tree), this mutant wrongly blocks it - exactly the "narrowing
;; regressed something that used to pass" failure invariant 3 exists to
;; catch, independent of anything to do with the dirty-path machinery.
(defn- mutant-narrower-than-old-gate! [dir adapters]
  (let [{:keys [behind]} ((:rev-counts! adapters))]
    (when (and (pos? behind) (even? behind))
      ((:merge! adapters)))))

(defn- non-vacuity-check-narrower-than-old-gate []
  (let [clean-odd-behind-scenario {:behind 5 :dirty-paths #{} :merge-changed-paths #{}}
        merge-calls (atom 0)
        adapters {:rev-counts! (fn [] {:ahead 0 :behind 5})
                  :dirty-paths! (fn [] #{})
                  :merge-changed-paths! (fn [] #{})
                  :merge! (fn [] (swap! merge-calls inc) {:success true})
                  :surface! (fn [_msg] nil)
                  :log! (fn [& _parts] nil)}]
    (mutant-narrower-than-old-gate! (mk-tmp) adapters)
    (if (and (oracle-old-gate-should-mutate? clean-odd-behind-scenario) (zero? @merge-calls))
      (println "non-vacuity confirmed: invariant 3's oracle would flag a mutant that regresses a state the old gate already allowed through (merge! did NOT fire when it must)")
      (do (println (str "NON-VACUITY FAILURE (narrower-than-old-gate mutant): expected the old-gate oracle to require reconciling and the mutant to violate it; merge-calls=" @merge-calls))
          (System/exit 1)))))

(non-vacuity-check-narrower-than-old-gate)

;; ── report ────────────────────────────────────────────────────────────────
(println (str "master_main_reconcile_lib property: " runs " runs"))
(if (empty? @failures)
  (println "ALL PROPERTIES HOLD")
  (do (println (str (count @failures) " PROPERTY FAILURE(S):"))
      (doseq [f (take 10 @failures)] (println f))
      (System/exit 1)))
