'use strict';

const fs = require('node:fs');
const path = require('node:path');

function slug(name) {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
}

function entryFileName(feature) {
  return `${slug(feature.name)}.generated.test.js`;
}

function scenarioCases(scenario) {
  if (scenario.examples && scenario.examples.length > 0) {
    return scenario.examples.map((row, index) => ({
      title: `${scenario.name} [${index + 1}]`,
      row,
    }));
  }
  return [{ title: scenario.name, row: undefined }];
}

// GENERATED entry points are plain CommonJS files run directly by Node's
// built-in test runner (`node --test`) - kept out of the extension's Vitest
// run so acceptance runs stay sequential and decoupled from the whole-suite
// unit run (engineering.prompt's Verification rule).
function generateEntryPointSource(feature, opts) {
  const runtimeModulePath = opts.runtimeModulePath || require.resolve('./runtime');
  const stepRegistryModulePath = opts.stepRegistryModulePath || require.resolve('./stepRegistry');
  const lines = [];
  lines.push("'use strict';");
  lines.push(`// GENERATED by specs/pipeline/generate.js from "${feature.name}" - do not edit by hand.`);
  lines.push("const { test } = require('node:test');");
  lines.push(`const { runScenario } = require(${JSON.stringify(runtimeModulePath)});`);
  lines.push(`const { createStepRegistry } = require(${JSON.stringify(stepRegistryModulePath)});`);
  lines.push(`const { registerSteps } = require(${JSON.stringify(opts.stepsModulePath)});`);
  lines.push(`const feature = ${JSON.stringify(feature)};`);
  lines.push('const registry = createStepRegistry();');
  lines.push('registerSteps(registry);');
  for (const scenario of feature.scenarios) {
    for (const { title, row } of scenarioCases(scenario)) {
      lines.push(`test(${JSON.stringify(title)}, async () => {`);
      lines.push(`  await runScenario(registry, feature, ${JSON.stringify(scenario)}, ${row ? JSON.stringify(row) : 'undefined'});`);
      lines.push('});');
    }
  }
  return lines.join('\n');
}

function writeEntryPoints(feature, outDir, opts) {
  fs.mkdirSync(outDir, { recursive: true });
  const outPath = path.join(outDir, entryFileName(feature));
  fs.writeFileSync(outPath, generateEntryPointSource(feature, opts), 'utf8');
  return outPath;
}

module.exports = { generateEntryPointSource, writeEntryPoints, entryFileName, scenarioCases, slug };
