/**
 * BL-1365: the ritual ledger's producer and store — the "independent cadence"
 * half of invariant 1.
 *
 * The split this file exists to enforce: MEASUREMENT accrues here, on the
 * daemon's own sweep, and is written durably. SELECTION (the volume/dominance
 * thresholds and the open-ticket suppression) happens at packet assembly, over
 * whatever the store currently holds. That is what makes "a ceremony that
 * never runs loses no measurement" true rather than aspirational: the ledger
 * does not care whether anybody read the last one, and a later ceremony sees
 * the earlier window's commits because they are still in the store.
 *
 * Sibling shape: contextTelemetryProducer.ts / turnProfileProducer.ts. Same
 * telemetry directory, same injected write seam, same thin CLI wrapper.
 */
import * as fs from 'fs';
import * as path from 'path';
import { execFileSync } from 'child_process';
import { RitualClassStats, RitualCommit, buildRitualLedger } from './ritualLedger';

export const RITUAL_LEDGER_STORE_FILE = 'ritual-ledger.json';

/** The sweep window. 45 days is the span the 2026-09-03 manual sweep used. */
export const RITUAL_LEDGER_WINDOW_DAYS = 45;

export interface RitualLedgerRecord {
  computedAt: string;
  windowDays: number;
  commitsScanned: number;
  ledger: RitualClassStats[];
}

export function ritualLedgerStorePath(telemetryDir: string): string {
  return path.join(telemetryDir, RITUAL_LEDGER_STORE_FILE);
}

export function readPersistedRitualLedger(telemetryDir: string): RitualLedgerRecord | null {
  try {
    const raw = fs.readFileSync(ritualLedgerStorePath(telemetryDir), 'utf8');
    const parsed = JSON.parse(raw) as RitualLedgerRecord;
    return Array.isArray(parsed?.ledger) ? parsed : null;
  } catch {
    // No ledger yet, or an unreadable one. Either way the ceremony proceeds
    // with no candidates rather than failing the shift close - the packet's
    // other findings are not this module's to block.
    return null;
  }
}

export function writeRitualLedger(telemetryDir: string, record: RitualLedgerRecord): void {
  fs.mkdirSync(telemetryDir, { recursive: true });
  fs.writeFileSync(ritualLedgerStorePath(telemetryDir), `${JSON.stringify(record, null, 2)}\n`, 'utf8');
}

/**
 * `COMMIT\t<subject>` followed by that commit's paths, one per line, blank
 * line between commits — `git log --format=COMMIT%x09%s --name-only`.
 * A commit touching no files (an empty commit) yields no paths and is
 * classified into nothing, which is correct: it participated in no ritual.
 */
export function parseRitualCommitLog(output: string): RitualCommit[] {
  const commits: RitualCommit[] = [];
  let current: RitualCommit | null = null;
  for (const line of output.split('\n')) {
    if (line.startsWith('COMMIT\t')) {
      current = { subject: line.slice('COMMIT\t'.length), paths: [] };
      commits.push(current);
    } else if (line.length > 0 && current) {
      current.paths.push(line);
    }
  }
  return commits;
}

/**
 * Merges are excluded on purpose: a merge's subject is generated by git, so a
 * ritual's merges would read as perfectly scripted and dilute the dominance of
 * the hand-made work underneath them.
 */
export function readRitualCommitLog(repoRoot: string, windowDays: number): string {
  try {
    return execFileSync(
      'git',
      [
        '-C',
        repoRoot,
        'log',
        `--since=${windowDays}.days.ago`,
        '--no-merges',
        '--format=COMMIT%x09%s',
        '--name-only',
      ],
      { encoding: 'utf8', stdio: ['pipe', 'pipe', 'pipe'], maxBuffer: 64 * 1024 * 1024 }
    );
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    process.stderr.write(`readRitualCommitLog: git log failed for ${repoRoot}: ${message}\n`);
    return '';
  }
}

export interface RitualLedgerProducerResult {
  commitsScanned: number;
  classes: string[];
}

/**
 * `readLogFn` and `writeFn` are injected side-effect seams (never
 * `*_FORCE_RESULT` env bypasses), so a test drives the real fold over a real
 * log body without a git repo or a writable telemetry dir.
 */
export function runRitualLedgerProducer(params: {
  repoRoot: string;
  nowIso: string;
  windowDays?: number;
  readLogFn?: (repoRoot: string, windowDays: number) => string;
  writeFn?: (record: RitualLedgerRecord) => void;
}): RitualLedgerProducerResult {
  const telemetryDir = path.join(params.repoRoot, '.swarmforge', 'telemetry');
  const windowDays = params.windowDays ?? RITUAL_LEDGER_WINDOW_DAYS;
  const readLogFn = params.readLogFn ?? readRitualCommitLog;
  const commits = parseRitualCommitLog(readLogFn(params.repoRoot, windowDays));
  const ledger = buildRitualLedger(commits);
  const record: RitualLedgerRecord = {
    computedAt: params.nowIso,
    windowDays,
    commitsScanned: commits.length,
    ledger,
  };
  const writeFn = params.writeFn ?? ((r: RitualLedgerRecord) => writeRitualLedger(telemetryDir, r));
  writeFn(record);
  return { commitsScanned: commits.length, classes: ledger.map((row) => row.ritualClass) };
}
