#!/usr/bin/env bb
;; Orphan janitor (operator stack): pure decision logic for reclaiming
;; leftover processes the fixture/agent reapers miss —
;;   1. operator_runtime.bb launched against a /tmp mktemp root (coder /
;;      acceptance dry-runs that never tore down; cwd often already deleted),
;;   2. hung `node --test …*.generated.test.js` acceptance runners left
;;      parented by WSL /init for many hours,
;;   2b. hung property-lane vitest trees (`vitest.properties.config.mjs`,
;;       npm/npx vitest, Vitest workers) under the host repo or a role
;;       worktree — parent-orphaned roots reap immediately; live-parented
;;       hangs still require the multi-hour age gate,
;;   3. disposable-root ancillaries fixture_reaper never sees (name is
;;      `tmp.*`, not aps-/sfvc-/bl404-): babysitter tmux/launch, babysitterd.sh
;;      pointed at a disposable root, any tmux -S under that root (e.g. BL-647
;;      fixture socks), front-desk bridge/bot, and stray `claude -n Babysitter`.
;;   4. leaked swarm `caffeinate -dims` daemons (BL-885): the resident-spy
;;      tunnel's idle-sleep-prevention process, tracked by only a single-slot
;;      pidfile - any crash/overwrite orphans the prior process with nothing
;;      left to reclaim it. Ownership is proven the same way as hung vitest
;;      (project-scoped cwd), with the pidfile's live pid as a never-reap
;;      exemption; no parent-orphaned fast path (PPID 1 is normal for every
;;      detached caffeinate, tracked or not).
;;
;; See orphan_janitor_sweep_lib.bb for process-table scan + kill wiring
;; (/proc on Linux, ProcessHandle on Darwin). Loaded by
;; operator_runtime.bb's always-alive tick (best-effort side action).
;;
;; GUARDRAILS: live-window / live-runtime-pid checked FIRST (decapitation);
;; never kill the host project's own operator_runtime or host ancillaries
;; (path must be a disposable root under /tmp/… or Darwin $TMPDIR
;; /var/folders/…/T/…).

(ns orphan-janitor-lib
  (:require [babashka.fs :as fs]
            [clojure.string :as str]))

;; Linux mktemp under /tmp, plus Darwin $TMPDIR (/var/folders/…/T/) checkouts
;; left by acceptance / BL-622 primary-launch sandboxes.
(def disposable-root-re
  #"(?:/tmp/(?:tmp\.[^/\s]+|aps-[^/\s]+|sfvc-[^/\s]+)|/var/folders/[^/\s]+/[^/\s]+/T/(?:tmp\.[^/\s]+|aps-[^/\s]+|sfvc-[^/\s]+|bl\d+-[^/\s]+))")

(defn tmp-project-root?
  "True when a path is a disposable mktemp/sandbox checkout — never the host repo."
  [project-root-arg]
  (let [p (str/trim (or project-root-arg ""))]
    (boolean (re-matches disposable-root-re p))))

(defn extract-disposable-root
  "First disposable root found in a cmdline or path, else nil.
   Covers /tmp/tmp.|aps-|sfvc- and Darwin /var/folders/…/T/tmp.|aps-|sfvc-|bl*-."
  [s]
  (re-find disposable-root-re (or s "")))

(defn operator-runtime-cmdline?
  [cmdline]
  (boolean (re-find #"operator_runtime\.bb\b" (or cmdline ""))))

(defn hung-acceptance-cmdline?
  "Acceptance entry points generated by specs/pipeline — long-lived hangs
   of these are never a live swarm role. Matches both `node --test …js`
   and bare `node …generated.test.js` (children left after the --test
   parent dies)."
  [cmdline]
  (let [c (or cmdline "")]
    (boolean (re-find #"\.generated\.test\.js(?:\s|$)" c))))

(defn hung-vitest-cmdline?
  "Property-lane vitest invocations and worker processes. Scoped to the
   host repo or a role worktree by callers before reaping."
  [cmdline]
  (let [c (or cmdline "")]
    (boolean
     (or (re-find #"vitest\.properties\.config\.mjs" c)
         (re-find #"(?i)\bnpm exec vitest\b" c)
         (re-find #"(?i)\bnpx vitest\b" c)
         (re-find #"(?i)\(vitest" c)
         (re-find #"(?i)node.*[/\\]vitest[/\\]" c)))))

(defn caffeinate-dims-cmdline?
  "True only for the exact `caffeinate -dims` invocation
   ensure_tunnel_caffeinate() spawns - a human's bare `caffeinate`, `-i`,
   `-d`, or any cmdline carrying extra args past -dims never matches (BL-885
   invariant 1: exact -dims argv is one of the required ownership signals)."
  [cmdline]
  (boolean (re-find #"(?:^|/)caffeinate\s+-dims\s*$" (or cmdline ""))))

(defn front-desk-bridge-or-bot-cmdline?
  "True for the headless bridge or front-desk bot entrypoints. Alone this
   also matches the host front desk — callers MUST still require a
   disposable root (tmp-ancillary-cmdline? / tmp-project-root?) before
   treating the process as reapable."
  [cmdline]
  (let [c (or cmdline "")]
    (boolean
     (or (re-find #"/extension/out/tools/start-bridge-headless\.js" c)
         (re-find #"/extension/out/tools/telegram-front-desk-bot\.js" c)))))

(defn tmp-ancillary-cmdline?
  "Front-desk / babysitter leftovers under a disposable checkout. Requires
   an extractable disposable root so host bridge/bot/babysitterd never match.
   Also covers worktree babysitterd.sh aimed at a temp root, and any tmux
   whose -S socket path sits under that root (BL-647 / swarmforge-coder
   fixture leftovers)."
  [cmdline]
  (let [c (or cmdline "")]
    (boolean
     (and (extract-disposable-root c)
          (or (re-find #"babysitter-tmux\.sock" c)
              (re-find #"/\.swarmforge/babysitter/launch\.sh(?:\s|$)" c)
              (re-find #"babysitterd\.sh(?:\s|$)" c)
              (re-find #"(?:^|[\s/])tmux(?:\s|$)" c)
              (front-desk-bridge-or-bot-cmdline? c)
              (and (re-find #"(?:^|\s)claude(?:\s|$)" c)
                   (re-find #"(?:^|\s)-n\s+Babysitter(?:\s|$)" c)))))))

(defn parse-operator-runtime-root
  "Extract the project-root argument after operator_runtime.bb in cmdline."
  [cmdline]
  (when-let [m (re-find #"operator_runtime\.bb\s+(\S+)" (or cmdline ""))]
    (second m)))

(defn parse-tmp-ancillary-root
  "Disposable root embedded in an ancillary cmdline (sock / launch / js / settings)."
  [cmdline]
  (extract-disposable-root cmdline))

;; Pure: tmp-rooted operator_runtime orphans. Live guards win first.
(defn reapable-tmp-operator-runtime?
  [{:keys [in-live-window-set? is-live-runtime-pid? tmp-project-root? stale?]}]
  (cond
    in-live-window-set? false
    is-live-runtime-pid? false
    (not tmp-project-root?) false
    (not stale?) false
    :else true))

(defn project-scoped-path?
  "True when cmdline or cwd is under the canonical host root or a registered
   role worktree (roles.tsv column 3)."
  [project-root cmd cwd]
  (let [root (str/trim (or project-root ""))
        roles-file (fs/path root ".swarmforge" "roles.tsv")
        worktrees (when (fs/exists? roles-file)
                    (->> (str/split-lines (slurp (str roles-file)))
                         (map #(get (str/split % #"\t") 2))
                         (remove nil?)
                         vec))
        canonical (fn [p]
                    (try (str (fs/canonicalize p)) (catch Exception _ (str p))))
        paths (distinct (cons (canonical root) (map canonical (or worktrees []))))
        in-path? (fn [s]
                   (boolean (and s (some #(str/starts-with? s %) paths))))]
    (or (in-path? cmd) (in-path? cwd))))

;; Pure: hung acceptance node --test runners.
(defn reapable-hung-acceptance?
  [{:keys [in-live-window-set? hung-acceptance? stale?]}]
  (cond
    in-live-window-set? false
    (not hung-acceptance?) false
    (not stale?) false
    :else true))

;; Pure: hung property-lane vitest trees under this project.
(defn reapable-hung-vitest?
  [{:keys [in-live-window-set? hung-vitest? project-scoped? stale?
           parent-orphaned?]}]
  (cond
    in-live-window-set? false
    (not hung-vitest?) false
    (not project-scoped?) false
    parent-orphaned? true
    (not stale?) false
    :else true))

;; Pure: disposable-root babysitter/bridge/bot/claude-Babysitter leftovers.
;; Front-desk bridge/bot that have already lost their supervisor (PPID 1 /
;; dead parent) skip the multi-hour age gate: they contend for the host's
;; fixed bridge port and produce production give-up emails within minutes,
;; while a still-parented fixture (live acceptance) stays protected by the
;; ordinary stale? path. Detached babysitter/tmux leftovers still require
;; stale? — PPID 1 is normal for those.
(defn reapable-tmp-ancillary?
  [{:keys [in-live-window-set? tmp-rooted-ancillary? stale?
           parent-orphaned? front-desk-bridge-or-bot?]}]
  (cond
    in-live-window-set? false
    (not tmp-rooted-ancillary?) false
    (and front-desk-bridge-or-bot? parent-orphaned?) true
    (not stale?) false
    :else true))

;; Pure: leaked swarm caffeinate -dims daemons (BL-885). Every ownership
;; signal must hold at once (invariant 1); no parent-orphaned fast path -
;; PPID 1 is normal for every detached caffeinate, tracked or not, so
;; staleness is never skipped for this class (invariant 3).
(defn reapable-leaked-caffeinate?
  [{:keys [in-live-window-set? caffeinate-dims? project-scoped? stale?
           is-live-caffeinate-pid?]}]
  (cond
    in-live-window-set? false
    (not caffeinate-dims?) false
    (not project-scoped?) false
    is-live-caffeinate-pid? false
    (not stale?) false
    :else true))
