#!/usr/bin/env bb
;; Orphan janitor (operator stack): pure decision logic for reclaiming
;; leftover processes the fixture/agent reapers miss —
;;   1. operator_runtime.bb launched against a /tmp mktemp root (coder /
;;      acceptance dry-runs that never tore down; cwd often already deleted),
;;   2. hung `node --test …*.generated.test.js` acceptance runners left
;;      parented by WSL /init for many hours,
;;   3. disposable-root ancillaries fixture_reaper never sees (name is
;;      `tmp.*`, not aps-/sfvc-/bl404-): babysitter tmux/launch, babysitterd.sh
;;      pointed at a disposable root, any tmux -S under that root (e.g. BL-647
;;      fixture socks), front-desk bridge/bot, and stray `claude -n Babysitter`.
;;
;; See orphan_janitor_sweep_lib.bb for process-table scan + kill wiring
;; (/proc on Linux, ProcessHandle on Darwin). Loaded by
;; operator_runtime.bb's always-alive tick (best-effort side action).
;;
;; GUARDRAILS: live-window / live-runtime-pid checked FIRST (decapitation);
;; never kill the host project's own operator_runtime or host ancillaries
;; (path must be a disposable root under /tmp/… or Darwin $TMPDIR
;; /var/folders/…/T/…).

(ns orphan-janitor-lib
  (:require [clojure.string :as str]))

;; Linux mktemp under /tmp, plus Darwin $TMPDIR (/var/folders/…/T/) checkouts
;; left by acceptance / BL-622 primary-launch sandboxes.
(def disposable-root-re
  #"(?:/tmp/(?:tmp\.[^/\s]+|aps-[^/\s]+|sfvc-[^/\s]+)|/var/folders/[^/\s]+/[^/\s]+/T/(?:tmp\.[^/\s]+|aps-[^/\s]+|sfvc-[^/\s]+|bl\d+-[^/\s]+))")

(defn tmp-project-root?
  "True when a path is a disposable mktemp/sandbox checkout — never the host repo."
  [project-root-arg]
  (let [p (str/trim (or project-root-arg ""))]
    (boolean (re-matches disposable-root-re p))))

(defn extract-disposable-root
  "First disposable root found in a cmdline or path, else nil.
   Covers /tmp/tmp.|aps-|sfvc- and Darwin /var/folders/…/T/tmp.|aps-|sfvc-|bl*-."
  [s]
  (re-find disposable-root-re (or s "")))

(defn operator-runtime-cmdline?
  [cmdline]
  (boolean (re-find #"operator_runtime\.bb\b" (or cmdline ""))))

(defn hung-acceptance-cmdline?
  "Acceptance entry points generated by specs/pipeline — long-lived hangs
   of these are never a live swarm role. Matches both `node --test …js`
   and bare `node …generated.test.js` (children left after the --test
   parent dies)."
  [cmdline]
  (let [c (or cmdline "")]
    (boolean (re-find #"\.generated\.test\.js(?:\s|$)" c))))

(defn tmp-ancillary-cmdline?
  "Front-desk / babysitter leftovers under a disposable checkout. Requires
   an extractable disposable root so host bridge/bot/babysitterd never match.
   Also covers worktree babysitterd.sh aimed at a temp root, and any tmux
   whose -S socket path sits under that root (BL-647 / swarmforge-coder
   fixture leftovers)."
  [cmdline]
  (let [c (or cmdline "")]
    (boolean
     (and (extract-disposable-root c)
          (or (re-find #"babysitter-tmux\.sock" c)
              (re-find #"/\.swarmforge/babysitter/launch\.sh(?:\s|$)" c)
              (re-find #"babysitterd\.sh(?:\s|$)" c)
              (re-find #"(?:^|[\s/])tmux(?:\s|$)" c)
              (re-find #"/extension/out/tools/start-bridge-headless\.js" c)
              (re-find #"/extension/out/tools/telegram-front-desk-bot\.js" c)
              (and (re-find #"(?:^|\s)claude(?:\s|$)" c)
                   (re-find #"(?:^|\s)-n\s+Babysitter(?:\s|$)" c)))))))

(defn parse-operator-runtime-root
  "Extract the project-root argument after operator_runtime.bb in cmdline."
  [cmdline]
  (when-let [m (re-find #"operator_runtime\.bb\s+(\S+)" (or cmdline ""))]
    (second m)))

(defn parse-tmp-ancillary-root
  "Disposable root embedded in an ancillary cmdline (sock / launch / js / settings)."
  [cmdline]
  (extract-disposable-root cmdline))

;; Pure: tmp-rooted operator_runtime orphans. Live guards win first.
(defn reapable-tmp-operator-runtime?
  [{:keys [in-live-window-set? is-live-runtime-pid? tmp-project-root? stale?]}]
  (cond
    in-live-window-set? false
    is-live-runtime-pid? false
    (not tmp-project-root?) false
    (not stale?) false
    :else true))

;; Pure: hung acceptance node --test runners.
(defn reapable-hung-acceptance?
  [{:keys [in-live-window-set? hung-acceptance? stale?]}]
  (cond
    in-live-window-set? false
    (not hung-acceptance?) false
    (not stale?) false
    :else true))

;; Pure: disposable-root babysitter/bridge/bot/claude-Babysitter leftovers.
(defn reapable-tmp-ancillary?
  [{:keys [in-live-window-set? tmp-rooted-ancillary? stale?]}]
  (cond
    in-live-window-set? false
    (not tmp-rooted-ancillary?) false
    (not stale?) false
    :else true))
